### ISSUE TITLE
[DLEK] La leçon envoyée n'est pas envoyée en copie à l'élève

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#10]
Quand l'élève envoie une leçon, il doit normalement recevoir une copie du message envoyé au correcteur. Mais cela ne fonctionne pas.

**Comment by axel584** [comment]
Je n'arrive pas à reproduire le problème (il me faudrait une autre adresse email avec un autre fournisseur d'accès que gmail), mais dans le mail que je reçois, je vois que je suis "en copie"
![image](https://cloud.githubusercontent.com/assets/1334088/15655539/519bf3ae-269e-11e6-880a-864cbbd85270.png)

(j'ai fait un compte élève "axel588")

**Comment by emmrichard** [comment]
Suis-je bête ! C'était parti dans les spams. Donc tout va bien, pas de bug !
