### ISSUE TITLE
Erreur sur le correcteur attribué dans la page administri

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#101]
Test fait sur le site de dev 
1. Je prends la fiche d'un élève en attente (n°7784), inscrit pour le DLEK.
2. Je me l'attribue
--> Je reçois bien les mails adressés à l'élève et au correcteur
3. Dans le panneau d'admin, c'est le nom d'un autre correcteur qui apparaît.
Pourtant, l'élève est bien dans ma liste et pas dans celle de l'autre correcteur. Ça semble donc être une erreur à l'affichage dans administri uniquement

**Comment by axel584** [comment]
@emmrichard : c'était un bug très con où dans une requête SQL un peu complexe, l'une des tables était préfixée par le nom de la base "ikurso", ce qui fait que ça te donnait le nom du correcteur de l'élève 7784 d'ikurso : 
http://ikurso.esperanto-jeunes.org/administri.php?celpersono_id=7784

Donc, c'était un bug qui ne pouvait pas avoir lieu en prod :-) mais je l'ai quand même corrigé ;-)
