### ISSUE TITLE
corriger le lien "section suivante" où la flèche n'est pas dans le bon sens

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#111]

**Comment by emmrichard** [comment]
Je crois que je l'ai fait.
Tu te souviens où c'était ?

**Comment by axel584** [comment]
En fait, c'est moi qui l'avait fait, c'était en bas de chaque section, j'avais fait un copier coller rapide qui faisait un truc du style : 

<< section précédent      << section suivante

au lieu de : 

<< section précédent      section suivante >>
