### ISSUE TITLE
Afficher les réponses en erreur dans le QCM

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#12]
Quand on remplit le QCM de la première leçon du DLEK, si des réponses sont erronées, on réaffiche la leçon 1 en gardant les réponses proposées et on barre en rouge les réponses fausses.
![screenshot 2016-05-30 a 18 08 52](https://cloud.githubusercontent.com/assets/1334088/15669832/91c287f2-2722-11e6-8c18-aee91b55dfbb.png)

**Comment by axel584** [comment]
@emmrichard : peux tu faire un style css et me donner un exemple de html à utiliser

**Comment by emmrichard** [comment]
Modifications à faire dans le html, pour chaque question avec une réponse erronnée : 
1. Entourer la question par un <span> et attribuer la classe "qcmerr" quand il est en erreur
Dans le cas du screenshot, on aurait 
<span class="qcmerr">01. Combien de syllabes y a-t-il dans 'viaj kukoj' ?</span>

2. Entourer la réponse fautive par un <span> et attribuer la classe "qcmerr".
Dans le cas du screenshot, on aurait 
<input type="radio" name="900 01" value="3">&nbsp;<span class="qcmerr">5</span>

**Comment by axel584** [comment]
y'a ça qui reste affiché : erreurs :Array ( )
Et le choix "pas de réponse" aussi est affiché dans les possibilités

**Comment by emmrichard** [comment]
Je n'ai pas vu cette erreur. Ça arrive quand ?

**Comment by axel584** [comment]
Sur la page : http://ikurso-dev.esperanto-jeunes.org/fr/cge/lec01.php
Juste avant le QCM, tu as le messages "erreurs : Array()" qui est un message de débuguage. Il doit avoir une ligne "print_r" dans le code qu'il faut supprimer.
Et dans les propositions pour chaque question, il y a le dernier choix qui est "(Pas de réponse)" qui devrait être caché.

ça devrait me prendre 30 secondes à corriger ce soir.

Bisous,

Axel
