### ISSUE TITLE
Ajouter les liens dans les menus

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#131]

**Comment by axel584** [comment]
@emmrichard : quels liens ? Est ce qu'on envoie sur la page "intro" ou bien sur la première leçon de chaque cours ?

**Comment by emmrichard** [comment]
Je parlais du menu qui est dans l'entête de la page. Je pense que ce serait mieux de laisser toujours la même chose, en l'occurrence la page de présentation du cours.
On pourrait avoir quelque part un lien vers la leçon à étudier mais il faudrait que le nom soit plus explicite, par exemple "aller à mon cours". Ce bouton-là pourrait être dans la page des données personnelles par exemple.
