### ISSUE TITLE
gérer la page d'intro

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#134]
http://localhost/ikurso/fr/cge/intro.php

Si la personne n'est pas connecté :
il faut afficher créer un compte OU "se connecter" si la personne a déjà un compte.
Si on clique sur "créer un compte", il faut ouvrir la popup de création de compte

Si la personne est connecté, on affiche juste "cmomencer ici à la première leçon, premiere section"

**Comment by emmrichard** [comment]
J'ai déjà commité ça tout à l'heure. 
@axel584 : Regarde en bas de la page si ça te convient.

Je propose de modifier un peut : ne pas parler des accents ici (pas la peine de dire à l'élève qu'il pourra peut-être avoir un problème avant qu'il commence. Il sera temps de lui en parler dans la première leçon).
Décaler le paragraphe sur les doc téléchargeables sous le bloc bloc.
Ainsi le bloc bleu avec les liens sera plus visible.
Qu'en dis-tu ?

**Comment by axel584** [comment]
ça me semble très bien :-)
