### ISSUE TITLE
Quand on a le message "compte non validé" sur la page de connexion, il faudrait pouvoir redemander le mail d'activation

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#135]
Cas testé : je crée un compte, mais je n'ai pas reçu le mail d'activation
Si j'essaie de me connecter, j'ai le message d'erreur suivant : 

![capture 2016-07-02 a 19 11 41](https://cloud.githubusercontent.com/assets/1328018/16541660/ffd1bacc-4088-11e6-9903-5e3a5acf6cb3.jpg)

Mais comme je ne trouve pas le mail, je suis bien embêtée...

Il faudrait que dans ce cas, on affiche sur cette fenêtre le bouton RENVOYER LE COURRIEL D'ACTIVATION

**Comment by axel584** [comment]
Je repousse à la V6, c'est à faire, mais pas indispensable immédiatement.
