### ISSUE TITLE
Comment passer les leçons sur le nouveau design

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#141]

**Comment by emmrichard** [comment]
La structure est la suivante : 
```
<div class="row">
	<article class="col s12 m10 l7 offset-m1 offset-l1">
		<section id="leciono-kapo">
```
titre
barre de progression dans la leçon (<ul id="progreso">)
```
		</section>
		<section id="leciono-enhavo">
``` 
contenu de la leçon, chaque section commençant par quelque chose comme : 
```
			if ($section=="1") {
			?>
			<section id="section1">
```
sans oublier le 
```
			<?php 
			} // fin section 7
			?>	

```
à la fin de chaque section (par exemple ici pour la 7)

Terminer par la section 
`		<section id="leciono-fino">`
dans laquelle on met le bouton pour terminer / enregistrer les réponses / envoyer au correcteur

Ensuite, c'est fini pour le bloc principal et on passe à la colonne suivante (sommaire) : 
```
	<aside class="col s12 m10 l3 offset-m1 push-l1">								
		<ul class="collapsible" data-collapsible="expandable">
```
et pour terminer on ferme les blocs : 
```
		</ul>				
	</aside>
</div>
```
et on appelle le dlekpiedo

**Comment by emmrichard** [comment]
Pour le bouton "terminé" / "enregistrer mes réponses" / "envoyer au correcteur" : 

Lorsque la leçon a été marquée comme terminée, il faut afficher le bouton #farita et on rendre invisible le bouton #registriEkzercaron_button / #sendiLecionon_button / #finiLecioneron_button
Pour ça, on utilise la class "hide" pour rendre invisible. J'avais mis au départ .visible / .invisible mais comme materialize utilise .hide j'ai modifié pour prendre celui-ci

**Comment by axel584** [comment]
J'ai copié la page wiki ici : 
https://github.com/axel584/ikurso/wiki/Structure-d'une-page-le%C3%A7on

@emmrichard : il faudrait savoir si on empeche d'enregistrer les exercices si on les a déjà enregistré une première fois car l'élève peut avoir envie de modifier ses réponses... Pareil pour le QCM ou l'envoie des leçons. Je dirai que le truc qui ne change pas ce serait le bouton "terminé", mais si l'élève a cliqué dessus, on pourrait imaginer que le bouton se transforme en un autre bouton qui indique que l'on n'a finalement pas fini la section (mais peut être dans un autre sprint)
