### ISSUE TITLE
Utiliser une nouvelle icône pour les pistes audio dans les cours

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#145]
Pour remplacer ceci : 
![capture 2016-07-03 a 00 54 20](https://cloud.githubusercontent.com/assets/1328018/16542802/c74523a8-40b8-11e6-804b-c555d9427f95.jpg)

**Comment by emmrichard** [comment]
Remplacer l'icône par un lecteur audio HTML5

**Comment by axel584** [comment]
Utiliser : http://www.schillmania.com/projects/soundmanager2/
