### ISSUE TITLE
Récupérer la date saisie dans sxangxipersoninformojn

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#150]
J'ai utilisé la fonction jquery qui affiche un calendrier, comme indiqué dans materialize, mais il reste à récupérer les données depuis cette zone de saisie

**Comment by axel584** [comment]
J'ai corrigé en utilisant un tableau créé à la main pour transformer les chiffres en noms de mois et inversement... il faut être prudent lors des tests et idéalement tester le plus de cas différent (Août, Janvier, Décembre)
