### ISSUE TITLE
Gérer le QCM dans la V5

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#157]
@emmrichard  : J'ai géré le QCM. Je pourrai l'améliorer en mémorisant les résutlats. Pour le moment c'est corrigé en Ajax, c'est à dire qu'on reste sur la même page et que les questions en erreur ont le style "qcmerr" d'ajouté. **Il faudrait que tu crées ce style** pour que l'affichage soit correct.

**Comment by emmrichard** [comment]
j'ai ajouté les styles
p.qcmerr : pour afficher la question en rouge lorsque la réponse est mauvaise
input[type="radio"] + label span.qcmerr : pour barrer la réponse lorsqu'elle est mauvaise

@axel584 :  pour que ça fonctionne bien, il faudrait que tu ajoute un <span class="qcmerr"> à l'intérieur du label correspondant à la réponse fausse, par exemple 
`<input type="radio" name="900 04" value="1" id="900 041"> <label for="900 041"><span class="qcmerr">ch</span></label>

**Comment by emmrichard** [comment]
Petit bug : lorsqu'on a cliqué une fois sur le bouton VÉRIFIER MES RÉPONSES, il reste affiché en gris, et semble donc désactivé, ce qui est surprenant quand on veut corriger des réponses du QCM.
@axel584 : est-ce qu'on pourrait laisser ce bouton en bleu tant que le qcm n'est pas complètement répondu sans erreur ?

**Comment by axel584** [comment]
@emmrichard  :
C'est un peu compliqué à faire. (l'affichage du bouton est assez déconnecté du résultat). 
En revanche, je peux faire en sorte que le bouton QCM ne soit jamais grisé.

Qu'en dis tu ?

**Comment by emmrichard** [comment]
@axel584 : On peut laisse le bouton en bleu dans ce cas.
