### ISSUE TITLE
Changer l'accueil pour que les élèves arrivent directement sur la dernière leçon étudiée

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#17]
- Faut il le mettre dans la page eniri ? 
- non car les gens qui sont déjà identifié doivent pouvoir accéder à leur leçon quand ils arrivent directement sur ikurso.esperanto-jeunes.org

**Comment by axel584** [comment]
Règle : 
- Si l'élève est "en cours", il arrive sur la dernière leçon non effectuée (donc dernière leçon faite +1)
- Si l'élève a terminé la dernière leçon mais que son correcteur n'a pas encore indiqué, on l'envoie sur sa page de données personnelles
- Si l'élève a terminé et que le correcteur a indiqué "a terminé", on l'envoie sur sa page de données personnelles

**Comment by emmrichard** [comment]
On pourra ensuite renommer cette page en "Tableau de bord", car il n'y aura pas que des données personnelles.

**Comment by axel584** [comment]
:+1:

**Comment by emmrichard** [comment]
Tu parles du cas où l'élève aurait terminé une leçon, mais que ça ne serait pas encore indiqué comme tel par le correcteur. En fait, ça, c'est ce qui se passe dans le cas du logiciel, mais pour le dlek, une fois que l'élève a envoyé sa leçon, on considère cette leçon comme terminée. 
Par la suite, si on met en place un système de correction sur le site, on pourra distinguer le cas d'une leçon terminée par l'élève (= il a envoyé ses exercices), du cas où elle a été corrigée. Par exemple si l'élève arrive sur le site alors qu'il avait la fois précédente envoyé ses exercices, on pourra différencier plusieurs cas 
1. L'élève a envoyé sa leçon, mais le correcteur n'a pas encore corrigé. On pourra dire "Vous avez terminé la leçon x, mais elle est encore en attente de correction". On laissera la possibilité d'accéder à la leçon suivante, mais on ne le mettra pas en avant sur le site.
2. L'élève a envoyé sa leçon, elle a été corrigée, et l'élève n'a pas encore lu la correction. On pourra dire "Votre correcteur a corrigé les exercices que vous avez envoyé" + un lien pour accéder à la correction. Et à la fin de la correction, un lien vers la leçon suivante.
3. L'élève a déjà lu la correction de la leçon précédente. On l'envoie directement vers la leçon suivante.
Dans le cas où l'élève a commencé une leçon, on se retrouve dans le cas 3.
