### ISSUE TITLE
Le code erreur apparaît en haut de la page

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#171]
Exemple sur http://localhost:8888/ikurso/fr/cge/lec01.php?section=8&erarkodo=21
![capture 2016-07-06 a 22 19 59](https://cloud.githubusercontent.com/assets/1328018/16633098/e2e01692-43c7-11e6-8f53-3d215fbeffc5.jpg)

**Comment by axel584** [comment]
Je pensais que tu ne voulais pas que le toast s'affiche en haut, du coup, j'ai été voir pour voir où s'affichait le toast avant de me rendre compte "tiens, c'est quoi ce chiffre en haut"... J'ai corrigé avant de comprendre que c'était justement ta demande :-) ça veut dire qu'il faut que j'aille me coucher ;)
