### ISSUE TITLE
Gérer le renvoi d'email de confirmation

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#177]
Remettre le bouton "renvoyer l'email de confirmation" sur la modal qui apparait après l'inscription et l'ajouter sur la modal de connection si on n'a pas validé son compte

**Comment by axel584** [comment]
@emmrichard : au final, est ce que c'est bien utile ? dans quel cas il pourrait ne pas avoir reçu le premier mail ? ça ne serait pas plus utile de l'ajouter dans l'interface d'administration ?

**Comment by emmrichard** [comment]
@axel584 : il y a sûrement plein de raisons. On peut l'avoir reçu dans les spams et supprimé par erreur. 
Je dirais que c'est plutôt sur la fenêtre de connexion, car c'est là qu'on peut avoir un message qui dit de cliquer sur le lien du mail. Et là, si on ne donne pas la possibilité à l'utilisateur de résoudre son problème, il sera coincé. 
Mais c'est en doublon avec #135
