### ISSUE TITLE
Ajouter un bouton "Commencer le cours"

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#179]
A partir de la page "données personnelles", si aucun cours n'a été choisi (champ "kurso" à vide), ajouter un bouton "Commencer le cours en 10 leçons"

@emmrichard : pourrais tu me faire le bouton (tu n'es pas obligé de le mettre en "hide" car j'ajouterai les conditions autours en php pour ne l'afficher que quand cela s'y prête.

**Comment by emmrichard** [comment]
@axel584 : pour le bouton, il suffit que tu utilises ce code : 
<p><a href="<?php echo $vojo;?>fr/cge/intro.php" class="btn waves-effect waves-light" >Commencer le cours en 10 leçons</a></p>
