### ISSUE TITLE
Permettre aux utilisateurs non inscrits d'accéder aux cours

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#189]
- [x] Sur la page de présentation du cours, ajouter la liste des leçons, et permettre à ceux qui ne sont pas inscrits de consulter les pages du cours
- [ ] Ne pas proposer à ceux qui sont connectés de créer un compte

**Comment by axel584** [comment]
@emmrichard  : on l'a fait ça non ? (si oui, à fermer et à mettre dans la V8)

**Comment by emmrichard** [comment]
Non, ça n'est pas fait. Je m'en occupe.
