### ISSUE TITLE
[inscription] Faire un système d'inscription indépendant du cours (= Créer un compte)

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#19]
Dans un premier temps, on peut faire un système de création de compte indépendant en laissant la possibilité de créer un compte en s'inscrivant de manière classique...

Je pense qu'il faudrait garder dans le formulaire d'inscription uniquement les champs obligatoires du formulaire actuel (les champs facultatifs serait toujours ajoutable dans le menu "informations personnelles")

On ajouterait un système de validation de l'adresse email pour éviter les erreurs dans les adresse email. Quand l'utilisateur clique sur le lien de validation, il arrive directement sur la page "informations personnelles"

**Comment by axel584** [comment]
Pour la V3, on va documenter ce qu'on va développer. Les workflows en fonction des cours etc.

**Comment by emmrichard** [comment]
J'ai commencé la doc dans gdocs : ikurso-Nouvelle procédure d'inscription
Bonne lecture !

**Comment by axel584** [comment]
http://code.tutsplus.com/tutorials/how-to-implement-email-verification-for-new-members--net-3824 
http://youhack.me/2010/04/01/building-a-registration-system-with-email-verification-in-php/

**Comment by axel584** [comment]
popup de création de compte : 
Si l'adresse email rentrée existe déjà sur un compte et que le compte n'est pas validé => on propose de renvoyer le message de validation
Si l'adresse email rentrée existe déjà sur un compte et que le compte a déjà été validé, on vérifie l'identifiant et le mot de passe.
   Si l'identifiant et le mot de passe correspond au compte, on connecte la personne et on fait comme si c'était la popup de connection
   Si l'identifiant correspond mais pas le mot de passe, on affiche un truc du style "Le compte existe déjà mais avec un autre mot de passe, si vous ne vous souvenez plus de votre mot de passe, cliquez sur "Réinitialiser le mot de passe" => et on affiche le bouton pour la popup de réinitialisation du mot de passe
   Si l'identifiant ne correspond pas, on affiche un truc du style "Cette adresse email est déjà utilisé pour l'identifiant "XXX" (et là, il se démerde avec ça)

popup de connection au compte
Si l'identifiant existe mais avec un mauvais mot de passe, on fait apparaitre le bouton "Réinitialiser le mot de passe")

**Comment by axel584** [comment]
bon, en fait, j'ai pas fait exactement comme ça, mais j'ai fait un truc similaire, on verra à l'usage si certains sont perdus.
