### ISSUE TITLE
Faire le design pour ces pages

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#199]
- [x] fr/gerda/konsiloj.php

- [x] fr/gerda/konfirmo.php?kazo=2&lec=1

- [x] fr/gerda/lasu00.php

- [ ] fr/cge/temaro.php (référencée dans fr/gerda/konsiloj.php)

**Comment by emmrichard** [comment]
et aussi 
- [ ] fr/gerda/vocabula.php
