### ISSUE TITLE
Afficher un message plus explicite quand on valide son compte

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#206]
les élèves semblent valider plusieurs fois leur compte, est ce que le message est assez explicite ?

**Comment by axel584** [comment]
@emmrichard : je me demande si ce n'est pas un problème de couleur. Le message "votre compte est bien validé" est sur un fond bleu pastel et je me demande si c'est pour cela que les élèves le valident plusieurs fois sans comprendre que c'est bien validé.

**Comment by emmrichard** [comment]
Je viens de faire un test. J'ai un message d'erreur quand je clique sur le
lien d'activation :

*Warning*: Cannot modify header information - headers already sent by
(output started at /arthur/sites/ikurso/aktivigi.php:1) in
*/arthur/sites/ikurso/aktivigi.php* on line *23*

Je crois qu'il ne faut pas chercher plus loin :-)

**Comment by axel584** [comment]
Du coup, comme on l'a corrigé, on va dire qu'il n'y a rien à faire :-)
