### ISSUE TITLE
tests de début de cours

### ISSUE THREAD

**Issue by CERIZO** [axel584/ikurso#209]
Ajouter un test "image" au début des cours pour réviser le vocabulaire (voir fichier exemple, avec photos vraiment libres, en PJ envoyées à Axel)

[tests images exemples.pdf](https://github.com/axel584/ikurso/files/401142/tests.images.exemples.pdf)

[photos test.pdf](https://github.com/axel584/ikurso/files/401143/photos.test.pdf)

**Comment by CERIZO** [comment]
Précisions sur ces fichiers "tests" : ce sont bien des exemples, il faut bien sûre affiner et corriger pour faire des phrases propres et justes : je m'y atèle et vous proposerai une relecture. 
L'idée est que des tests sur 5 à 7 images soient en début de cours, en auto correction, permettant de reprendre le vocabulaire de la leçon précédente et d'anticiper un peu sur la suite. Donc test 1 en début de leçon 2, test 2 en début de leçon 3 etc ...
Pour les images, voici les 5 premières du premier test : pouvez vous les ouvrir ? est ce le bon format ? la bonne taille ? j'ai choisi un téléchargement "taille moyenne" pour ne pas avoir des photos trop lourdes(dans le fichier "photos  tests" j'ai référencé les photos pour avoir sources et auteurs, pour nous, car l'usage dans le cas de I kurso serait totalement libre. Je me renseigne si il faut citer les auteurs des photos). 
![cafe du matin](https://cloud.githubusercontent.com/assets/20816022/17431074/5288f8f0-5af8-11e6-87c5-73143a08a150.jpg)
![pain](https://cloud.githubusercontent.com/assets/20816022/17431089/67b58dba-5af8-11e6-8d96-241f07a097c7.jpg)
![oiseaux](https://cloud.githubusercontent.com/assets/20816022/17431095/6fe84c66-5af8-11e6-897d-0bd33d67d56f.jpg)
![etude garcon](https://cloud.githubusercontent.com/assets/20816022/17431103/805849c0-5af8-11e6-988a-0040933d71d5.jpg)
![instruistino](https://cloud.githubusercontent.com/assets/20816022/17431107/83ae185c-5af8-11e6-920d-769b64715443.jpg)

**Comment by emmrichard** [comment]
Pour la taille, je pense que 300 px de large devrait suffire pour
l'affichage, mais comme il faudra que je les recadre pour qu'elle aient
toutes les mêmes dimensions, c'est très bien d'avoir des photos un peu plus
grandes (env. 450 à 500px c'est suffisant).

**Comment by axel584** [comment]
Pour les copyrights, on pourrait les rassembler dans une page à part (par exemple, la page "qui sommes nous" qui est prévu en bas de l'écran)...

**Comment by emmrichard** [comment]
J'ai créé une maquette dans le site dans une nouvelle page : cge/qcm02.php?section=0

@axel584 : dis-moi si ça te convient pour mettre en place le qcm

**Comment by axel584** [comment]
@emmrichard : j'avais pensé utilisé un carroussel de materialize css : 
http://materializecss.com/carousel.html

Tu pourrais essayer de mettre ce que tu as fait dans un carroussel ?

L'idée serait d'ensuite mettre un "style" sur les bonnes réponses qui passerait à la question suivante en jquery (peut être avec un toast pour dire "bravo" et un autre style sur les mauvaises réponses pour dire "essaye encore")

**Comment by axel584** [comment]
Est en lien avec le #109

**Comment by CERIZO** [comment]
http://materializecss.com/carousel.html

Tu pourrais essayer de mettre ce que tu as fait dans un carroussel ?

L'idée serait d'ensuite mettre un "style" sur les bonnes réponses qui passerait à la question suivante en jquery (peut être avec un toast pour dire "bravo" et un autre style sur les mauvaises réponses pour dire "essaye encore") ==> si je vais sur le carroussel, ce n'est pas trés clair pour moi, novice en informatique, mais l'idée du "bravo" et "essaye encore" est sympa ...si ça peut tourner informatiquement, c'est super ! à suivre
