### ISSUE TITLE
Retirer le système des X et Unicode

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#21]
Retirer également le "boitier" en haut à gauche qui permet de choisir. (on peut aussi retirer le lien "aide" qui fait redondance avec l'entrée dans le menu)

**Comment by axel584** [comment]
Penser à changer dans la base de données le champ "sistemo"

**Comment by axel584** [comment]
le retirer aussi de l'inscription, de la page d'administration, des données personnelles etc.

**Comment by emmrichard** [comment]
Supprimer l'explication sur la méthode en x dans les pages : 
page intro.php, dans l'onglet Préambule
page http://ikurso-dev.esperanto-jeunes.org/fr/gerda/lasu00.php
page helpo.php#accents

**Comment by emmrichard** [comment]
En revanche il manque les accents dans la page
http://ikurso-dev.esperanto-jeunes.org//helpo.php?temo=iloj
