### ISSUE TITLE
Ajouter des phrases clés de conversation courante

### ISSUE THREAD

**Issue by CERIZO** [axel584/ikurso#210]
Ajouter les phrases de la leçon 5 en leçons 1, 2, 3 
leçon 1 : comment dire "bonjour-bonsoir"
leçon 2 : comment ça va ?
leçon 3 : autres

**Comment by axel584** [comment]
Je me suis occupé des 2 premiers, mais j'ai laissé la troisième partie dans la leçon 5 car il n'y a pas d'urgence à apprendre "je via sano"

**Comment by CERIZO** [comment]
ok vu
