### ISSUE TITLE
Manque une section 11 dans la leçon 3 du dlek

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#218]
![capture 2016-08-05 a 00 10 22](https://cloud.githubusercontent.com/assets/1328018/17420095/18b9052c-5aa1-11e6-8cea-2079246d1e1d.jpg)

**Comment by axel584** [comment]
@emmrichard  : Euh, ça me semble bien ici :  http://ikurso.esperanto-france.org/fr/cge/lec03.php

**Comment by emmrichard** [comment]
C'est ma base qui n'est pas à jour, alors
