### ISSUE TITLE
Améliorer la présentation du tableau dans la leçon 5 / section 2

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#219]
actuellement, c'est du texte dans des balises <pre>

**Comment by axel584** [comment]
@emmrichard : je ne comprends pas ce qu'il faudrait faire, mais tu l'as peut être déjà fait ?

**Comment by emmrichard** [comment]
Non, pour l'instant c'est fait avec des balises "pre" et c'est affiché à l'ancienne en police Courrier avec des lettres pour faire les traits. Et c'est pas beau !

**Comment by axel584** [comment]
Est ce qu'une image ne serait pas mieux ?
Un truc comme ça : http://www.dab.hi-ho.ne.jp/t-wata/moees/bildo/fig-korelativo.png

Il faudrait peut être regarder sur d'autres sites comment les corrélatifs sont expliqués ?
