### ISSUE TITLE
Détailler l'explication sur le COD afin d'expliquer ce qu'est le COD

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#230]
L'idée est d'améliorer la page suivante : 
http://ikurso.esperanto-france.org/fr/cge/lec02.php?section=2

**Comment by CERIZO** [comment]
pour le COD, voici mes propositions ..à retravailler aussi ..je me suis inspirée de l'allemand ...
J'aurais aimé ajouter des petits signes pour "a savoir", "rappel" ...mais ça ne passe pas au collage ...donc texte brut ..j'envoie par mail aussi.

L'accusatif en espéranto a la fonction d'indiquer le rôle que joue un mot ou un groupe de mot dans la phrase : sujet / verbe/complément. 
L'accusatif signe en fait un complément particulier appelé « complément d'objet direct » ou COD (revoir vos vieux cours de français !!! ).
$Petit rappel : le COD est un complément essentiel du verbe (on ne peut ni le déplacer ni le supprimer dans la phrase). Il se place souvent en réponse à la question « quoi ? », « qui ? ». Il est introduit directement, c'est-à-dire sans préposition (contrairement au COI = complément d'objet INDIRECT introduit par une préposition)

Exemple de COD : le chat (sujet) mange (verbe)LA SOURIS(COD) (le chat mange QUOI ? La souris qui est COD
En espéranto : la kato mangxas la muson (remarquer que les articles ne portent PAS la marque n !)

Exemple de COI : le chat court derrière la souris : le chat court derrière ...(préposition) quoi ? Il y a une préposition, donc ce ne peut être un COD, même si on a la question « quoi » !
En espéranto : la kato kuras post la muso (sans N donc!)

$A savoir : quand un groupe de mot (nom+adjectifs) est COD, en espéranto, il prend la marque N de l’accusatif. Mais ATTENTION : le N ne s'ajoute PAS à l'article, ni aux chiffres ! 
Par contre, l'adjectif, le pronom personnel prennent la marque de l'accusatif. Le pluriel prend aussi la marque de l'accusatif.
Quelques exemples 
la bruna kato kaptas la grisaN musoN
BelaN veteroN ni havas nun (remarquer l'inversion des mots ! Rendue possible par ce marquage de l'accusatif)
Petro havas liajN malnovajN librojN. Li havas tridek librojn

$A savoir : Avec le verbe être qui n’a jamais de complément d’objet direct, on n’utilise pas l’accusatif, car le verbe être implique que le sujet et l’attribut sont « équivalents ».
« Elle est belle. » équivaut à « Elle = belle. »
A vous de jouer en trouvant la bonne déclinaison : utiliser le menu déroulant  -© pour ajouter ou non un n (exemple en allemand) 
1. Georg geht in die Schule, aber er hat kein -©Rucksack. 
2. 
3. 
4. 
5.
6. S
7. 
8.
9. 
10. 



2.3. Autres compléments ATTENTION ? PARTIE PAS CLAIRE !
En général les compléments autres que les compléments d’objet direct (par exemple, les compléments circonstanciels) sont introduits par des prépositions. Dans ce cas, la préposition nous donne une indication de la fonction de ce complèment.
Exemple : je dîne A la maison / Je vais DANS ma chambre / Je pars A 7h.
En espéranto, comme en français, ces compléments ne sont pas des COD et donc, ILS NE PORTENT PAS LA MARQUE DE L ACCUSATIF ...En règle générale !  
Nous verrons ces prépositions à la leçon …..(donner le N°) .
$A savoir  Comme en allemand, pour ceux qui ont pratiqué, en espéranto, l'accusatif ne sert pas QUE pour indiquer le COD : la terminaison « n » s'utilise aussi pour indiquer un changement de lieu, une date, un mouvement, un temps, voire même pour remplacer une préposition (ça peut être pratique!) Mais n'allons pas trop vite ! Voyons déjà l'usage simple et courant en espéranto : l'indication du complément d'objet direct !!! la suite aux prochaines leçons !
A RETENIR DONC 
-COD sans préposition ⇒ usage de la marque N de l'accusatif sur le nom, les adjectifs, les pronoms possessifs
-Complèments avec préposition (sauf spécificité) : pas de N e
==> partie à placer AVEC L ACCUSATIF
exercice

**Comment by CERIZO** [comment]
sur cette proposition faite assez rapidement, vous aurez remarqué qu'il y a des erreurs à corriger de faute de frappe en français et en Eo ...à repasser à la moulinette (ex :"post" au lieu de "malantaux" etc). reste aussi les phrases exercices ..je regarde pour proposer qqc. A suivre
