### ISSUE TITLE
Bug connexion d'un élève qui a terminé Gerda

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#232]
Dès que je me connecte avec le compte d'un élève qui a fini Gerda, j'arrive sur la page 
http://localhost:8888/ikurso/null

![capture 2016-08-09 a 22 30 44](https://cloud.githubusercontent.com/assets/1328018/17532482/12293428-5e81-11e6-833b-e6a529655dc3.jpg)

**Comment by emmrichard** [comment]
Cependant si je reviens tout de suite sur le site, je suis correctement connectée, et ma page Données personnelles est correcte : 
![capture 2016-08-09 a 22 32 27](https://cloud.githubusercontent.com/assets/1328018/17532514/439fb0c2-5e81-11e6-9a09-1f403336a3be.jpg)

**Comment by emmrichard** [comment]
Même problème pour un élève qui a fini le DLEK.
On arrive sur la page http://localhost:8888/ikurso/null

**Comment by axel584** [comment]
C'est corrigé pour moi.
