### ISSUE TITLE
Gérer l'affichage des noms longs dans le diplômes

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#235]
Sinon on peut avoir des débordements

![attestation-nom](https://cloud.githubusercontent.com/assets/1328018/17533130/c255c68e-5e83-11e6-95c4-04eaf0370576.jpg)

**Comment by axel584** [comment]
@emmrichard  : Tu penses corriger ça comment ? 
On peut utiliser une police plus petite au dela d'une certaines longueurs
si longueur du nom < X caracètres : police très grande
si longueur > X et < Y : police moyenne
si longueur <Y : toute petite police et on tronque à N caractères

**Comment by emmrichard** [comment]
@axel584 : j'ai cherché si on ne pouvait pas faire ça en CSS (on ne sait jamais), mais apparemment non. Donc je pense que je vais faire ça en Js et utiliser une taille de caractères différente selon la longueur du nom.

Tronquer le nom me paraît une mauvaise idée, car il s'agit du nom de l'élève donc ce serait bizarre de tronquer dans ce cas.

**Comment by axel584** [comment]
@emmrichard : c'est fait en php et ça génère une image, donc pas possible en CSS ou en JS, faut faire ça en php.
C'est dans le fichier diplome.php à la ligne 55 : 
imagettftext($image, 48, 0, 300, 300, $noir, 'fonts/OpenSans-Light.ttf', $nom);

Pour calculer la taille d'une chaîne de caractère, il faut utiliser la fonction strlen.
Donc, au pif, faudrait faire un truc comme ceci : 
if (strlen($nom)<**20**) {
imagettftext($image, **48**, 0, 300, 300, $noir, 'fonts/OpenSans-Light.ttf', $nom);
} elseif (strlen($nom)<**40**) {
imagettftext($image, **38**, 0, 300, 300, $noir, 'fonts/OpenSans-Light.ttf', $nom);
} else {
imagettftext($image, **28**, 0, 300, 300, $noir, 'fonts/OpenSans-Light.ttf', $nom);
}

J'ai mis en gras les valeurs à changer par test successif...

Pour ce qui est de tronquer, ça dépend à combien de caractère... si c'est un nom super long, c'est possible que ce soit une blague... Enfin de toutes façons, si on tronque pas, la bordure du diplome le fera pour nous :-)
