### ISSUE TITLE
Mentionner l'envoi des exercices dans l'épilogue

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#236]
On pourrait changer le titre "Épilogue" en 
![capture 2016-08-09 a 23 00 07](https://cloud.githubusercontent.com/assets/1328018/17533459/0c29269c-5e85-11e6-801e-733122fd49ab.jpg)

@axel584 : qu'en dis-tu ?

**Comment by axel584** [comment]
Si tu vois une phrase à mettre pour expliquer les choses, ça peut être bien oui.
