### ISSUE TITLE
Impossible d'envoyer l'examen final du DLEK

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#237]
Il y a juste un bouton pour enregistrer les réponses mais rien pour les envoyer

**Comment by axel584** [comment]
C'est un problème de base de données, il faut ajouter ces deux lignes : 
UPDATE `lecioneroj` SET lasta=0 WHERE `leciono_id` = 71 and ordo=1;
INSERT INTO `lecioneroj` (`id`, `leciono_id`, `titolo`, `tipo`, `ordo`, `unua`, `lasta`) VALUES (NULL, '71', 'Bravo !', 'TEKSTO', '2',0,1);

Je m'en occupe pour dev et prod, je te laisse les insérer chez toi en local.
