### ISSUE TITLE
[inscription] Inscription au cours, Conditions d'utilisations

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#24]
Je me disais aussi qu'on pourrait ajouter à l'inscription au cours une sorte de case à cocher pour "les conditions générales d'utilisation" où l'on demanderait aux élèves de respecter les correcteurs bénévoles, être assidu à l'apprentissage et informer son correcteur en cas d'absence prolongé ou d'abandon. 
 L'idée est de responsabiliser un peu les élèves en leur faisant comprendre que les correcteurs sont des êtres humains qui dévouent du temps pour aider les élèves à leur apprentissage

**Comment by axel584** [comment]
Je repousse à la V6, on a tenu 15 ans sans :-)

**Comment by axel584** [comment]
J'ai demandé à Stackoverflow : 
http://stackoverflow.com/questions/38785252/how-can-i-remove-a-element-when-another-appear

**Comment by axel584** [comment]
Il faut changer le texte ici : 
http://ikurso.esperanto-france.org/fr/cge/lec01.php?section=8

On va remplacer : 

```
L’inscription n’est indispensable que si vous désirez faire appel à un correcteur. Si c’est le cas, remplissez soigneusement le formulaire ci-dessous après avoir effectué les exercices de la leçon. Une confirmation d’inscription vous parviendra par courrier électronique dans les prochains jours. Attendez de la recevoir avant de commencer la deuxième leçon.

Par ailleurs nous vous proposons de vous abonner à une lettre d’information mensuelle sur les activités liées à l’espéranto. Cette lettre est éditée par l’association Espéranto-France et hébergée par Yahoogroupes. Vous pouvez donc très facilement vous désabonner à tout moment et la protection des données personnelles (adresse électronique par exemple) est assurée correctement.
```

Par : 

```
L’inscription n’est indispensable que si vous désirez faire appel à un correcteur. Les correcteurs sont bénévoles et s'occupent chacun d'un nombre limité d'élèves. En demandant un correcteur, vous vous engagez à suivre le cours avec assiduité et informer votre correcteur en cas d'absence prolongée. Votre correcteur est là pour répondre à vos questions sur la langue espéranto, mais aussi sur l'utilisation que l'on peut faire de l'espéranto. N'hésitez pas à vous présenter et faire connaissance.

Bon apprentissage !
```

**Comment by emmrichard** [comment]
@axel584 : j'ai modifié le texte, mais tu avais parlé aussi d'une case à cocher. On mettrait ça où ?

**Comment by axel584** [comment]
Finalement, ce n'est peut être pas la peine de mettre une case à cocher... Je ne pense pas que ça aurait changé le comportement du petit suisse :-)
