### ISSUE TITLE
Corriger les entités dans les sujets des mails

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#240]
![capture 2016-08-09 a 23 38 40](https://cloud.githubusercontent.com/assets/1328018/17535367/5f1b2536-5e8e-11e6-87c5-ed14d1fd8a94.jpg)
![capture 2016-08-09 a 23 11 22](https://cloud.githubusercontent.com/assets/1328018/17535368/5f2df10c-5e8e-11e6-8d03-ebcd9bcb47bb.jpg)

**Comment by axel584** [comment]
@emmrichard : je n'arrive pas à reproduire le problème, ça s'affiche correctement sur gmail. Tu utilises quoi ?

**Comment by emmrichard** [comment]
@axel584 : j'ai vu ça sur mailinator. Et comme leur page est affichée en Windows-1252 je pense que c'est à cause de ça.
Je pense qu'on ne pourra rien aux webmails qui utilisent n'importe quel encodage, donc on peut considérer que c'est bon et fermer.

**Comment by axel584** [comment]
j'ai essayé de mettre une entité html, mais ça ne marche pas, ça s'affiche &eacute; ... donc on laisse tomber
