### ISSUE TITLE
[cours] Ajouter une section dans la première leçon avec saluton, kiel vi fartas, mi fartas bone, kiu vi estas

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#25]
On rentre dans les changements pédagogiques...

**Comment by axel584** [comment]
Ajouter cette section après la leçon 1.6 (et avant le QCM)
Prendre le petit tableau de la section 5.1 et ajouter "Kiu vi estas ?" "Mi estas Marko" / "Mi estas Ana" / "Saluton Marko"

**Comment by CERIZO** [comment]
oui, bien à cet endroit ...
