### ISSUE TITLE
dans la notation des leçons, donner un champ qui permet d'estimer en minute le temps passé pour cette leçon

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#252]
ajouter une colonne dans "tasko_leciono" et un champ sur la page pour les leçons cge ou gerda.

Le but est de pouvoir a terme donner une estimation du temps pris pour chaque leçon (surtout utile pour les cours de 3ème niveau)

Avec l'issue #273 ça sera calculé automatiquement, ce n'est donc pas forcement utile.

**Comment by emmrichard** [comment]
@axel584 : ça sert encore à quelque chose, ça ?
