### ISSUE TITLE
version à télécharger à corriger

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#254]
Sur la page : 
http://ikurso.esperanto-france.org/fr/elsxutoj.php

> salut,
> 
> Je suis passé sur la page de téléchargement (cours, exercices, ...) et pas un n'était disponible (une page d'erreur s'affiche quand je clique sur les liens). Serait-il possible de remettre ces liens à jour?
> 
> 
> Merci!!
> Bonne journée!!

**Comment by emmrichard** [comment]
J'ai vérifié : tout est bon.

**Comment by axel584** [comment]
Moi je tombe sur une erreur pour ces deux fichiers : 

```
Cahier d'exercices du cours en dix leçons (pdf - 223Ko)
Lexique Kurso de Esperanto / Cours en dix leçons (pdf - 55Ko)
```

**Comment by emmrichard** [comment]
zut, c'est les 2 seuls liens que je n'avais pas testé :-)
