### ISSUE TITLE
Un élève qui a terminé ne doit plus avoir de correcteur attitré

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#255]
Voir cas de l'élève #7700 (DLEK)

- [ ] Quand l'élève a terminé, il ne doit pas avoir le nom de son correcteur sur la page "Données personnelles"

- [ ] Si l'élève veut de nouveau faire le cours, il doit demander un correcteur comme pour un tout nouvel élève. 

Vérifier que c'est correct pour Gerda aussi.

**Comment by axel584** [comment]
Je pense plutôt qu'un élève ne devrait avoir qu'un seul correcteur atitré pour un cours donné et le garder même s'il décide de renvoyer des leçons de son cours.

**Comment by emmrichard** [comment]
@axel584 : On peut fermer alors ?
