### ISSUE TITLE
Ajouter le nom de l'élève dans le titre de la leçon

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#259]
Actuellement on a par exemple "lec01", il faudrait avoir "lec01 de xxxxx"

**Comment by axel584** [comment]
ça doit être bon, mais il faut tester et ce n'est pas évident : 
 il faut faire des comptes utilisateurs, remplir la première leçon et l'envoyer en demandant un correcteur) et il faut faire ça pour chaque cours

**Comment by emmrichard** [comment]
Résultat des tests : 

DLEK : le nom est bien ajouté dans la leçon 1 mais pas dans les suivantes. 
Dans la leçon 1, il manque le commentaire de l'élève.
Si j'envoie à nouveau la leçon 1 par la suite, il y a bien le commentaire, mais le nom de l'élève n'est pas mis dans l'objet du message.

Gerda : même problème

 niveau 3 : lorsque le correcteur est attribué, la leçon 1 n'est pas automatiquement envoyée. J'ai refait une deuxième fois cette leçon et cette fois, le mail est parti. Mais il n'y a pas le nom de l'élève dans l'objet du message.

**Comment by axel584** [comment]
oki... A noter aussi que l'élève peut envoyer plusieurs leçons avant qu'un correcteur lui soit attribué (ce qui sera impossible quand j'aurai fait le moteur d'attribution de correcteurs)

Et il faut aussi vérifier que quand on attribue un correcteur, le numéro de la leçon sur la fiche élève est bien renseigné (le numéro est "extrait" de la chaîne de caractère du titre du mail qui est à une position différente suivant le cours...)

Mais je vais corriger les problèmes que tu m'as remonté avant de refaire les tests.
