### ISSUE TITLE
Corriger l'ordre des réponses dans les mails des exercices

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#260]
Par exemple dans l'examen final (leçon 10 de DLEK), les réponses sont classés par ordre alphabétique.
On a donc ceci : 
1. amiko:
amie

10. filo
filino

11. patro
patrino

12. amiko

.... etc ... et ensuite : 
19. bona
malbona

2. butiko:
boutique

20. bela
malbela

21. nova
malnova

... etc... pour terminer par : 
6. kiu:
qui

7. multa
beaucoup

8. babilema:
bavard

9. legita:
lu

**Comment by emmrichard** [comment]
ça semble spécifique à l'examen final. J'ai retesté l'envoi de la leçon 2 en remplissant tous les champs et c'est correct.
Retester les envois des autres leçons.

**Comment by axel584** [comment]
@emmrichard : est ce que c'est mieux maintenant que @meunx a corrigé la fonction ekzerco ?

**Comment by emmrichard** [comment]
@axel584 : j'ai testé. C'est corrigé.
