### ISSUE TITLE
L'élève qui demande un correcteur pour Gerda n'apparaît pas dans la liste "en attente"

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#261]
Cas testé : élève qui a terminé DLEK et qui fait le chapitre 1 de Gerda<.
Il n'apparaît pas dans l'onglet "attendent un correcteur" de administri.php

dans la table personoj, on a kurso=GR et rajtoj=S

@axel584 : dans ce cas on devrait avoir rajtoj=P, il me semble ?

**Comment by axel584** [comment]
Effectivement, quand un élève "demande" un correcteur, il faudrait mettre à 'P' son champ "rajtoj". Dans la plupart des cas, ça ne changerait rien car il est déjà à "P" (Personoj = Valeur par défaut quand on s'inscrit), mais s'il a déjà suivi un cours avant, il est passé à S (Studento) et il faut le refaire passer à P pour qu'il apparaisse dans la liste des élèves en attente d'un correcteur.
