### ISSUE TITLE
Bug du correcteur affiché quand l'élève en a eu 2

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#262]
Cas testé : un élève suit le cours DLEK avec Correcteur-1, puis  quand il a terminé, il s'inscrit à Gerda, pour lequel on lui attribue Correcteur-2.
Dans sa page de données personnelles, c'est uniquement Correcteur-1 qui est affiché.

**Comment by emmrichard** [comment]
Mais la leçon est bien envoyée à Correcteur-2

**Comment by meunx** [comment]
J'ai pensé que ce bug serait rapidement corrigé et je pense l'avoir fait (la correction, pas le bug)

**Comment by meunx** [comment]
Pour info, au cas où, le correcteur mentionné sur le certificat de réussite du cours DLEK reste le bon.

**Comment by emmrichard** [comment]
J'ai testé de mon côté. C'est bon.
