### ISSUE TITLE
Ajouter des libellés pour les différentes notes de l'évaluation

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#275]
- intérêt de la leçon

1. Trop barbant 
2. Plutôt ennuyeux.
3. Moyen.
4. Assez intéressant
5. Génial ! J'ai adoré !

- difficulté de la leçon 

1. Les doigts dans le nez !
2. Assez facile. 
3. Quelques difficultés mais dans l'ensemble je m'en suis sorti.
4. Assez difficile. 
5. Trop compliqué. Je m'en suis arraché les cheveux !

**Comment by CERIZO** [comment]
oui, sympa ...cette évaluation apparaît quand ? car on pourrait imaginer aussi que ceci apparaisse à chaque leçon avec des smiles ?

**Comment by axel584** [comment]
A chaque fois que l'élève envoie sa leçon à son correcteur, il tombe sur une page comme celle ci : 
http://ikurso-dev.esperanto-france.org/fr/cge/konfirmo.php

Et il peut mettre une note à la leçon et surtout laisser un commentaire... C'est une véritable mine d'or car la plupart des élèves se permettent de signaler une difficulté ou une erreur dans le texte du cours. C'est comme cela qu'on a eu des élèves qui nous ont signalé qu'il manquait une majuscule à un mot sur un texte qui n'avait pas changé depuis 13 ans... (bon, c'est pas une grosse erreur, mais c'est toujours vexant de se dire que personne ne l'a signalé avant)

**Comment by axel584** [comment]
@emmrichard  : j'ai mis les libellés mais si tu as envie d'ajouter des styles (avec des couleurs ?)  ou simplement regarder comment j'ai stylé pour avoir deux colonnes et corriger au besoin, je te laisse faire.
les libellés sont mis grâce à une fonction dans ikurso.js
Si on voulait ajouter un style différent pour chaque valeur, on pourrait faire un truc comme ça : 

```
    if ($(this).val()==1) {
      $("#libelle_intereso").html("1. Trop barbant");
      $("#libelle_intereso").addClass("style_a_ajouter");
   }
```

Je te laisse juger si c'est nécessaire ou pas.
