### ISSUE TITLE
simplifier l'introduction du cours en 10 leçons

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#276]
http://ikurso.esperanto-france.org/fr/cge/intro.php

Retirer les formulations pompeuses, l'historique inutile (et qui donne l'impression que les cours est un cours vieillot), les passages idiots sur le fait qu'il faut une adresse internet... bah oui, c'est un cours en ligne, c'était peut être surprenant il y a 20 ans, mais aujourd'hui c'est une évidence qu'un cours en ligne ne se fait pas par la poste.

**Comment by CERIZO** [comment]
coucou : j'ai travaillé sur le texte d'intro ..encore un peu long, je vous laisse ajouter votre patte et les infos utiles (où trouver des clubs proches de chez soi, on me le demande et comment avoir les accentuations en dehors du cours) ...à vos plumes
Texte ci dessous car pas sûre que le fichier joint soit passé ?
Cours en 10 leçons
_AXEL A ECRIT : Retirer les formulations pompeuses, l'historique inutile (et qui donne l'impression que les cours est un cours vieillot), les passages idiots sur le fait qu'il faut une adresse internet... bah oui, c'est un cours en ligne, c'était peut être surprenant il y a 20 ans, mais aujourd'hui c'est une évidence qu'un cours en ligne ne se fait pas par la poste._
Préambule
Voici un cours en 10 leçons pour vous initier à l'espéranto. Le défi est que, à la fin de ce parcours, vous puissiez faire des phrases simples, comprendre de courts textes ou conversations, voire de correspondre avec des étrangers espérantistes ! Pas moins !  à l’origine, il s'agissait  d’un cours par correspondance pour anglophones, adapté par la suite au français puis au courrier électronique par la société québécoise d’espéranto (ESK).La version 2016 est une proposition complètement relookée, mais qui a gardé l'esprit de départ : simplicité et efficacité. Et ce en mettant à profit les connaissances pédagogiques nouvelles et les évolutions du web ! 

L’étape suivante sera alors de suivre le cours Gerda malaperis qui vous permettra d’assimiler les connaissances acquises et vous ouvrira la porte à une utilisation active de la langue. Ou encore (et même en parallèle) ce sera de rencontrer les espérantistes de votre département, ville, région ...rien de tel que l'échange humain tout de même pour avancer ! 
Pour connaître les adresses des associations ou clubs proches de chez vous, voir le lien suivant **(????y a t-il un lien?)**
Comment suivre ce cours (titre)
Ce cours de compose de 10 leçons alternant du son, des textes, des images, des vidéos (???). Les leçons sont des combinaisons d'explications sur le fonctionnement de la langue, des apports de vocabulaire et de points grammaticaux. Une large place est donnée aux exercices de mise en pratique, aux QCM, aux tests afin que vous puissiez pas à pas évaluer vos progrès. Le cours peut être utilisé par des débutants en mode autodidacte, cependant nous vous conseillons de demander l’aide d’un tuteur qui corrigera vos exercices, sera disponible pour répondre à vos questions et vous suivra tout au long de votre apprentissage.
Comment demander l'appui d'un correcteur ? (titre)
1-  créer un compte sur ce site en indiquant au minimum une adresse électronique valide permettant les échanges entre vous et le correcteur. Remarque : ce cours peut être utilisé sur smarphone (????oui ou pas ? ou sur d'autres appareils ? à PRECISER°
2-Commencer la première leçon et faites les exercices demandés. Envoyez les via le site
3-Un correcteur vous sera attribué à partir de ce moment. Un délais de réponse de quelques jours est possible à l'issu de ce premier envoi, si il n'y a plus de places disponibles (les correcteurs ne suivent qu'un nombre restreint d'élèves pour une meilleure qualité des échanges).
4- attendez d'avoir reçu la première correction pour poursuivre votre apprentissage : c'est important, car le correcteur vous donnera des informations et consignes qui pourront vous éviter bien des erreurs. Ceci ne doit pas vous empêcher de lire les cours suivants avant ce retour de correction, et de déjà préparer les exercices.

ATTENTION F les cours sont GRATUITS ! Mais, nous mobilisons des correcteurs, qui mobilisent du temps ! Aussi, l'inscription à ce cours en 10 leçons est un engagement de votre part. Aussi nous vous demandons de travailler  régulièrement (une leçon par semaine au minimum)  et de prévenir votre correcteur en cas de retard ou d’empêchement à poursuivre le cours. Car de son coté, votre correcteur s'est engagé à vous suivre et donc à mettre tout en œuvre pour le bon déroulement de ces 10 leçons. C'est un contrat tacite réciproque qui relève du respect mutuel !
Note au sujet de la typographie (Titre)
Vous trouverez dans la page d’aide des informations utiles sur la façon d’utiliser les lettres accentuées.
Dans les exercices, il suffit de taper la lettre suivie d’un x par exemple : cx, sx, ux… pour obtenir automatiquement la lettre accentuée correspondante. 
Sur votre clavier, si vous voulez pouvoir taper les lettres accentuées, nous vous proposons plusieurs solutions :
-
-
Consultation hors ligne
Vous pouvez télécharger une version du cours au format PDF pour consultation hors ligne :
Cours en dix leçons (PDF - 476Ko)
