### ISSUE TITLE
qcm : afficher le récapitulatif de toutes les questions à la fin

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#283]
On n'affiche dans ce cas que les bonnes réponses, accompagnées éventuellement d'une courte explication. Cela permet à l'élève de les revoir et de prendre des notes avant de passer à la suite de la leçon.

**Comment by axel584** [comment]
@emmrichard  : Dans le cas des "images", on ne peut pas afficher les "questions" en récapitulatif... ou alors il faut afficher des vignettes des images ?
L'idée me semble bonne pour les QCM de type "phrase"... mais difficile à mettre en oeuvre pour les images.

**Comment by emmrichard** [comment]
@axel584 : Je pensais juste juste afficher les images et la bonne réponse associée à chaque image.

**Comment by emmrichard** [comment]
@axel584 : je pense qu'on peut fermer
