### ISSUE TITLE
qcm : sur un écran large, on peut voir 2 questions à la fois

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#284]
![qcm-ecran-large](https://cloud.githubusercontent.com/assets/1328018/17830744/2f00a9bc-66d5-11e6-9e7e-b2ecd57febfd.jpg)

**Comment by emmrichard** [comment]
La photo est également rogné, sur les petits écrans aussi : 
![capture 2016-08-20 a 12 54 51](https://cloud.githubusercontent.com/assets/1328018/17830754/63294ae6-66d5-11e6-8a01-859bb3bef944.jpg)

**Comment by emmrichard** [comment]
Je suppose que c'est un pb de style

**Comment by axel584** [comment]
oui, normalement, ça prend toutes la place disponible, c'est bizarre.

**Comment by emmrichard** [comment]
C'est bon en fait. Il faut juste rafraîchir l'affichage quand on change la
taille de la fenêtre.
