### ISSUE TITLE
Améliorer la page données personnelles pour afficher les boutons qui envoit vers un cours

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#290]
Tester si l'élève est en cours, pas encore commencé et déjà fini.
Si pas encore commencé (pas de nuna_kurso) mais inscrit sur kurso de esperanto, faire un petit baratin pour expliquer qu'il va bientôt recevoir un correcteur
si par encore commencé (pas de nuna_kurso) mais pas inscrit à un cours, lui proposer les 2 cours
Si commencé (correcteur reçu) et inscrit à kurso de esperanto, lui expilquer comment envoyer sa leçon
Si commencé et inscrit à un autre cours : afficher le nom de son correcteur et un bouton pour accéder à sa leçon
Si fini le cours : afficher le diplome

si pas encore fait gerda malaperis, mais leçon 10 finie (CG ou KE), afficher le lien pour commencer le cours gerda malaperis

**Comment by emmrichard** [comment]
Déjà fait en partie dans #242

**Comment by emmrichard** [comment]
Ce qui est déjà fait et les cas que j'ai testés (en local) : 

1. Élève inscrit au Kurso, mais qui n'a pas commencé : on affiche le nom du correcteur, le nom du cours + info "pas encore commencé" (cas de test ：DIDINE) 
2. Élève inscrit au Kurso, et qui attend un correcteur (cas de test : Zioux) : on affiche les boutons pour commencer soit le DLEK soit Gerda ==> RESTE À CORRIGER : on ne devrait pas afficher ces boutons dans ce cas
3. Élève qui a abandonné le Kurso ==> CAS À GÉRER / TESTER
4. Élève qui a terminé le Kurso mais pas encore commencé Gerda (ni demandé de correcteur pour Gerda) (cas de test : kiox) : on affiche le lien pour l'attestation et le bouton COMMENCER GERDA
5. Élève qui est en cours du DLEK (cas de test : MarineP) : lien pour accéder à la leçon à étudier
6. Élève qui a fini le DLEK mais pas encore inscrit à Gerda (cas de test : besaj) : on affiche le lien vers l'attestation + bouton COMMENCER GERDA
7. Élève qui a abandonné le DLEK (cas de test : aze) : on affiche la dernière leçon étudiée, mais on ne met pas de lien vers la leçon à étudier
8. Élève qui a terminé le Kurso et qui est en d'étudier Gerda (cas de test : Chimpee) : on affiche le correcteur actuel, le lien pour l'attestation du Kurso et le lien vers la leçon de Gerda à étudier
9. Élève qui a terminé le DLEK et qui est en d'étudier Gerda (cas de test : magnaneria) : on affiche le correcteur actuel, le lien pour l'attestation du DLEK et le lien vers la leçon de Gerda à étudier
10. Élève inscrit à Gerda et qui n'avait pas suivi ni le Kurso ni le DLEK avant (cas de test : magbaad) : on affiche le bouton COMMENCER LE COURS EN 10 LEÇONS et le bouton COMMENCER GERDA ==> là, il y a un bug, car dans ce cas, on devrait considérer que l'élève a commencé Gerda puisque l'inscription à Gerda se fait à la fin du premier chapitre, donc il faudrait afficher le lien vers la leçon de Gerda à étudier (ou plutôt afficher une info disant qu'un correcteur va être attribué)
11. Élève qui a terminé le cours DLEK et le cours Gerda : À RETESTER. Normalement on affiche les liens vers les attestations de DLEK et de Gerda
12. Élève qui a terminé le cours Kurso et le cours Gerda : À RETESTER. Normalement on affiche les liens vers les attestations de Kurso et de Gerda
13. Élève qui a terminé le cours DLEK et qui a abandonné cours Gerda : À TESTER. Normalement on affiche le lien vers l'attestations de DLEK, mais rien pour Gerda
14. Élève qui a terminé le cours Kurso et qui a abandonné cours Gerda : À TESTER. Normalement on affiche le lien vers l'attestations de Kurso, mais rien pour Gerda
15. Élève qui a abandonné cours Gerda et qui n'avait pas suivi d'autre cours avant : À TESTER. Normalement on n'affiche pas de lien vers la leçon à faire ni d'attestation

@axel584 : Peux-tu vérifier si ça te paraît correct ?

**Comment by emmrichard** [comment]
J'ai terminé les tests des cas 11 à 15
