### ISSUE TITLE
Bug IE

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#295]
J'ai fait un test au boulot et il me signale deux problèmes : 
- une balise </a> inutile
- l'utilisation de "for of" qu'IE ne doit pas aimer.

![bug_ie](https://cloud.githubusercontent.com/assets/1334088/17897573/f1774470-6954-11e6-8dd3-12b3a742c113.png)

**Comment by emmrichard** [comment]
Tu pense que corriger ça va résoudre le problème ?

Bisous
Emmanuelle

**Comment by axel584** [comment]
y'a qu'une façon de le savoir :-)
