### ISSUE TITLE
tester si l'utilisateur utiliser une vieille version d'IE et afficher un message d'erreur

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#297]
https://fr.wikipedia.org/wiki/User-Agent
https://openclassrooms.com/forum/sujet/connaitre-le-navigateur-du-client-95772

Afficher ce message pour les versions d'IE 9 et plus ancienne.

**Comment by emmrichard** [comment]
Trouvé ça récemment, qui a le mérite d'être simple : 



Reste à tester si c'est efficace. 
Changer le texte car "vous utilisez un navigateur obsolète" n'est pas très flatteur.
