### ISSUE TITLE
Message affiché en cas d'erreur dans le formulaire de contact

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#3]
1. Le message d'erreur recouvre partiellement le formulaire. 
2. Le message ne correspond par toujours à l'erreur (même texte pour plusieurs erreurs), et il est en espéranto

**Comment by axel584** [comment]
Quels genres d'erreur dans le formulaire de contact permet de reproduire le problème ? une capture d'écran ?

**Comment by emmrichard** [comment]
Exemple : on envoie le message avec un des champs vide. On a toujours le même message d'erreur.
![capture 2016-05-30 a 23 35 51](https://cloud.githubusercontent.com/assets/1328018/15658665/6bb5700a-26bf-11e6-989d-017fbeb54b2c.jpg)

**Comment by emmrichard** [comment]
Je vois toujours le message en espéranto.
![Uploading capture 2016-05-31 à 21.48.01.jpg…]()

**Comment by axel584** [comment]
Désolé, c'est le workflow de déploiement qui est un peu compliqué (je développe et test en local, je commit sur github, je récupère sur le serveur dans un répertoire et je copie ce répertoire sur l'espace ikurso-dev... )
J'avais oublié une ou deux étapes, c'est corrigé, la correction est bien sur ikurso-dev maintenant.

**Comment by emmrichard** [comment]
ok. C'est bon, maintenant
