### ISSUE TITLE
Le nouveau qcm ne fonctionne pas sur mobile

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#302]
Impossible de sélectionner un choix, que ce soit le qcm du début de la leçon 2 ou le qcm de la leçon 1

**Comment by axel584** [comment]
Et maintenant ?

**Comment by emmrichard** [comment]
C'est bon. J'ai testé les deux qcm sur mon téléphone et l'ipad. J'aurai juste une correction à faire sur la typo, car le gris n'est pas assez visible.
