### ISSUE TITLE
améliorer l'ergonomie du toast pour le qcm

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#304]
Il faudrait idéalement afficher le toast près du qcm, car on on est obligé de déplacer le regarde du qcm vers le coin de l'écran, puis revenir sur le qcm

**Comment by axel584** [comment]
Je ne pense pas que ce soit possible avec un toast... Mais on peut peut être faire un système similaire avec une div que l'on affiche pendant 2000 ms avant de la supprimer : https://api.jquery.com/delay/

**Comment by axel584** [comment]
@emmrichard : Apparement c'est possible de changer la position du toast :
http://stackoverflow.com/questions/33566041/materialize-css-change-position-of-toast-dialog
https://github.com/Dogfalo/materialize/issues/1518

Et bonne nouvelle (pour moi), c'est du CSS :-) Je te refile donc le bébé

**Comment by emmrichard** [comment]
@axel584 : merci, c'est trop gentil :-)

J'ai corrigé pour les grands écrans seulement. Sur le téléphone, on laisse affiché en bas de l'écran, car c'est très bien comme ça.
