### ISSUE TITLE
Ajouter une section supplémentaire dans chaque leçon "gerda" pour l'envoi des exercices

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#306]
Il faudrait ajouter une section qui s’appellerait "Épilogue", "Envoi des exercices" ou "Récapitulatif"

"Envoi des exercices" me plaît bien car ça a le mérite d'être clair et ce n'est pas un "épilogue" (contrairement au cours en 10 leçons) car on ne rappelle pas ce qui a été vu dans la leçon.

On pourrait ajouter sur cette page un message à l'intention des personnes qui ne sont pas connecté.

**Comment by emmrichard** [comment]
Il reste à ajouter un message pour ceux qui ne sont pas connectés.
