### ISSUE TITLE
mieux expliquer la différence entre les corrélatifs en -u et en -o

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#310]
J'ai eu du mal à comprendre les notes du chapitre 5.2 qui semblent un peu contradictoires avec la leçon (suffixe "u" utilisé pour des choses : "kiun frukton ...") alors que la leçon précise que ce suffixe est "réservé" pour des individus. J'ai posé la question en parallèle à mon correcteur

**Comment by emmrichard** [comment]
Modifier la présentation de la leçon 5 pour faire référence à ce qui aura déjà été vu dan les 4 premières leçons.
