### ISSUE TITLE
corriger le toast du QCM

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#318]
Très bonne idée les QCM avec la réponse immédiate.Et pour atteindre la perfection, je suggère que le bravo soit sur fond vert et , en cas d'erreur, d'écrire essayeZ encore car tout le cours est à la deuxième personne du pluriel.

@emmrichard  : ça te semble pertinent ?

**Comment by emmrichard** [comment]
@axel584 : différencier la couleur pour une réponse bonne et mauvaise, ça me paraît mieux. Ce qui serait bien aussi, c'est d'afficher le toast à côté du QCM plutôt que dans le coin (comme dans le cours de 3e niveau)

**Comment by axel584** [comment]
@emmrichard : tu as une idée de comment gérer les couleurs ? Pour ce qui est de la position, tu t'en es déjà occupé...

**Comment by axel584** [comment]
@emmrichard : ça me semble correct maintenant, on ferme cette issue ?

**Comment by emmrichard** [comment]
Reste à faire : vérifier si c'est possible d'afficher une couleur différente pour les bonnes et les mauvaises réponses.

**Comment by axel584** [comment]
@emmrichard  : Je ne vois pas comment faire ça car on affiche le même toast pour les messages d'erreur ou les bonnes réponses dans le QCM... Je serais assez d'avis pour clore cette issue pour le moment.
