### ISSUE TITLE
commentaire non envoyé au correcteur

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#325]
Apparement, le commentaire que l'on peut saisir à la fin de la leçon n'est pas envoyé au correcteur.
Vérifier ce point.

**Comment by axel584** [comment]
à tester

**Comment by emmrichard** [comment]
J'ai testé l'envoi de commentaire pour toutes les leçons du DLEK. Pas de problème.
@axel584 : tu avais reçu un cas précis ? Sinon on peut considérer qu'il n'y a pas de bug.
