### ISSUE TITLE
coquille leçon 9 sur cge

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#327]
Du rimarkojn. La unua, neutila : legxopropono venas de la Parlamento, kiam la iniciato estas ministr-devena, oni devus gxin kvalifiki legx-projekto. La dua, eble pli utila : Paska Renkonti o ? La vorto devas esti renkontigxo, sed la "gx" ne aperas sur mia ekrano.

**Comment by emmrichard** [comment]
Dans l'exercice 9.8, supprimer la remarque en bleu, car il faut écrire en français

**Comment by emmrichard** [comment]
J'ai corrigé les bugs. 
En ce qui concerne la première remarque, je ne suis pas sûre qu'il faille corriger (le texte ne dit pas que c'est le ministre qui a proposé la loi)
@axel584 : je te laisse fermer si ça te paraît bon
