### ISSUE TITLE
bug leçon 6

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#332]
Evaluation de la leçon :6 (5/3) : Le premier exercice n'est pas apparu dans le récapitulatif final. Je l'ai donc "copié-collé" dans la partie "correspondance avec le correcteur". Par ailleurs, l'audio fonctionne bien pour la leçon mais, comme pour le chapitre précédent, pas dans le dernier texte (après les exercices). Globalement, les leçons sont agréables et la difficulté progressive. Merci pour votre investissement pour la diffusion de cette langue de partage ! :-)

**Comment by emmrichard** [comment]
Autre bug dans cette leçon : dans l'exercice 1, la numérotation commence à 8. Voir on n'aurait pas perdu un exercice en passant sur le nouveau design.

**Comment by emmrichard** [comment]
Pour l'exercice 1, ça commence bien au 8 car le premier exercice est dans la partie 6.4 Révision des correlatifs

**Comment by emmrichard** [comment]
J'ai vérifié : le premier exercice apparaît bien dans le récapitulatif.
En revanche, le dernier exercice (6.17 Exercice 4) apparaît au tout début du récapitulatif.

**Comment by emmrichard** [comment]
Pour l'ordre des exercices, le problème était dans l'exercice 6.4
IL fallait mettre 27 comme numéro de cette question.
Donc en base, on a pour la leçon une champ kodo = ekz06_00 (on devrait avoir ekz06_27)

**Comment by emmrichard** [comment]
Ça ne me paraît pas nécessaire parce que ça concerne juste l'affichage du récapitulatif de la leçon, donc pour les élèves qui l'ont déjà fait, ils ne vont pas revenir dessus. Le plus important c'est que ça soit corrigé dans le site.
