### ISSUE TITLE
problème sur la date de naissance

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#333]
un élève semble dire que l'année de naissance n'est pas prise en compte quand il la modifie.

@emmrichard : peux tu tester ça ?

**Comment by emmrichard** [comment]
@axel584 : J'ai testé en prod, et ça fonctionne correctement.
Cependant sur ma page, le bouton ENREGISTRER LES MODIFICATIONS était sous la ligne de flottaison, et l'élève n'a donc peut-être pas validé. On pourrait améliorer la mise en page pour que le bouton soit visible ou alors qu'il y ait une information pour rappeler de valider

**Comment by axel584** [comment]
lié à #418

**Comment by axel584** [comment]
https://gist.github.com/JesseRWeigel/04e37cd5eb6f98f37c98870715be5721

**Comment by emmrichard** [comment]
Corrigé avec la saisie de date HTML5
