### ISSUE TITLE
centrer les vidéos youtube

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#335]
Celle de la leçon 01 dans le CGE, mais aussi celles de la leçon 4 du cours 3ème niveau

**Comment by emmrichard** [comment]
@axel584 : je ne comprends pas pourquoi centrer ? Si on la centre dans la colonne, il faudrait aussi centrer les questions qui sont en-dessous.

**Comment by axel584** [comment]
Effectivement, ce n'est pas vraiment nécessaire
