### ISSUE TITLE
afficher correctement le nombre de mots restants

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#336]
Dans le cours de 3ème niveau, à la leçon 1, on affiche un nombre de mots restant à rédiger, cet affichage utilise le champ "data-error" du textarea et se trouve ratatiné quand il est trop long.
Idéalement, il faudrait écrire "restas X vortoj por verki" mais ça ne s'affiche pas bien.

**Comment by emmrichard** [comment]
J'ai corrigé l'affichage sur une ligne en ajoutant des espaces inseccable. Mais il reste que utiliser le champ data-error n'est pas l'idéal, car ça s'affiche pas  au bon endroit, ou plutôt ça ne bouge pas quand on tape plusieurs lignes.

**Comment by axel584** [comment]
c'est bizarre parce que ça devrait être fait pour ça, non ?

Tu pourrais faire quelques maquettes sans CSS supplémentaire pour voir ce que ça donne ?

Bisous,

Axel

**Comment by emmrichard** [comment]
@axel584 : voilà quelque chose qui fonctionne bien. J'ai testé dans le navigateur.
Plutôt qu'utiliser le champ d'erreur, je te propose d'écrire la ligne qui va contenir le comptage des mots juste après le textarea.
Le code généré serait quelque chose comme ça : 
```
<div class="input-field col s12">
		<textarea id="res_ekzio_01" data-vortoj="100" class="materialize-textarea invalid" rows="20" name="res_ekzio_01" onkeyup="xAlUtf8(this)" style="height: 224.6px;"></textarea>
		<p class="nbvortoj">95 vortojn por verki</p>
	</div>
```
J'ai ajouté le nouveau style p.nbvortoj dans le CSS (commit 422e788d9f913e2fae7074c069acda15342b8e42)

**Comment by emmrichard** [comment]
C'est tout bon !
