### ISSUE TITLE
erreur sur gerda leçon 9

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#346]
Evaluation de la leçon :9 (4/2) : Vers la fin de la Rakonto, il semble y avoir une phrase tirée d'un précédent chapitre, qui ne devrait donc pas être là : "Bob: Pardonu min. Mi volas diri, ke io estas pli grava." De plus, il est dommage qu'il n'y ai pas version audio pour le Lasu min de ce chapitre. Bonne journée !

**Comment by emmrichard** [comment]
Il manquait en effet l'audio du chapitre 9 de "lasu min..." 

Pour la phrase en trop, ça a été corrigé par @meunx mais ça n'est pas encore en prod
