### ISSUE TITLE
Erreur sur les pages de vocabulaire pour un nouvel élève

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#361]
Le problème se pose pour un nouvel élève qui n'a pas encore de correcteur.
Comment reproduire : 
- Créer un nouveau compte
- Le valider, puis aller à la leçon 1 
- Lorsqu'on clique sur le bouton TERMINER, on obtient ce message : 
![capture 2016-10-22 a 22 18 30](https://cloud.githubusercontent.com/assets/1328018/19622246/b6bac444-98a5-11e6-9a6f-bb3cb34c2a33.jpg)

Cependant si je vais sur la page memoriVorotjn j'ai bien des mots à réviser.
Je vais dans la section 1.3 Vocabulaire, je clique sur TERMINER : j'ai de nouveau le message d'erreur.
Je me déconnecte du compte et je me reconnecte.
Je vais sur la page 1.7 Mes premiers mots et cette fois, plus de message d'erreur.

**Comment by axel584** [comment]
Corrigé : c'est la fonction qui ajoute les mots à réviser en base qui affichait des infos de débuguages que j'ai oublié de retirer et du coup, quand l'ajax affiche des trucs en trop, ça fout la grouille.
