### ISSUE TITLE
Ajouter un rappel sur la page de connexion

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#364]
Lorsqu'un élève se connecte, ou lorsqu'il arrive sur le site, afficher un message de rappel sur la page d'atterrissage. 
Ça pourrait être affiché en popup.
On pourrait dire par exemple "Vous avez ... mots à réviser" et proposer 2 boutons : RÉVISER MAINTENANT et VOIR PLUS TARD.

**Comment by axel584** [comment]
ça me semble un peu compliqué car quand l'élève arrive sur le site, il est renvoyé sur l'une des leçons du site... Peut être que l'on pourrait l'afficher juste en dessous de la liste des leçons et avant le titre de la section ?
Pourrais tu faire une maquette ? Un truc qui disparait quand on clique sur "Voir plus tard" ?

**Comment by emmrichard** [comment]
Dans ce cas, il y a déjà le bouton n MOTS À RÉVISER, donc ça ne me semble pas très utile.

**Comment by axel584** [comment]
ça, c'est du travail de pro ! :-)
