### ISSUE TITLE
Nouvelle page "Panneau de contrôle"

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#368]
Cette page contiendra certaines informations pour les administrateurs : 
- Afficher le "log / carnet de bord" avec des outils pour filtrer certaines informations  (n'afficher que les évaluations des élèves ou ne pas afficher les informations concernants l'outil de mémorisation du vocabulaire)
- liste des correcteurs avec leurs statistiques (nombre d'élèves en cours, total, fini, a abandonné) + possibilité de trier + liste des emails des correcteurs
- éditeur de leçon ? (dans un premier temps, on n'affiche que les informations sur une leçon donnée
- éditeurs d'élèves (qui pourrait remplacer ce qu'on a dans "Gestion des élèves") ?

On retirera les pages : 
- élèves en retards et correcteurs non connecté
- maintenance
- "dernier connecté" (sur la première page) car on peut l'obtenir par un filtre sur le carnet de bord

On utilisera un "SideNav" pour afficher les différentes pages ? ou bien mettre les pages dans le menu du haut (menu connexion) ? ou bien faire un "sommaire" comme on l'a pour les élèves ?

**Comment by emmrichard** [comment]
- [ ] Améliorer la typo dans le tableau (écrire un peu plus petit)
