### ISSUE TITLE
ajouter des exercices structuraux dans la leçon 8 du DLEK

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#370]
Ce qu'on pourrait faire, avant l'exercice de traduction, ce serait un exercice où on demande de compléter un tableau avec toutes les formes possibles pour un même verbe.

J'ai trouvé quelques petits exercices dont on pourrait s'inspirer pour faire pratiquer un peu les participes : 
http://www.ais-sanmarino.org/kursoj/s2/ilosc1/lec10.html

D'ailleurs plutôt que de faire faire systématiquement des exercices de traduction, est-ce que ça ne serait pas mieux de faire ce genre d'exercice ?
Ou peut-être ajouter un exercice du type de l'exercice 4 ou 5 du site ci-dessus, en plus des exercices qu'on demande dans la leçon 8 ?
Si on donne ces phrases à compléter par exemple : 
1. La infano, kiu dormas, estas __________ infano.
2. La fraŭlino, kiu kantas, estas __________ fraŭlino.
3. La junulo, kiu studos, estas ____________ junulo.

Ça peut être un premier exercice pour bien faire comprendre comment on forme les participes.

Pour ce qui est de la forme réfléchie, c'est ce qu'on présente dans la section 8.5 et c'est vrai qu'on n'a pas grand chose comme exercice là-dessus. Je pense qu'avant de faire l'exercice de traduction qu'on propose en 8.6 ce serait bien de faire un petit exercice plus simple qui permette de bien voir la différence entre si / li / ŝi avec des phrases simples. On pourrait reprendre les exemples qui sont donnés dans la section 8.5 et faire un exercice avec plusieurs phrases sur le même modèle.

D'ailleurs je pense que ça pourrait être bien d'ajouter des petits exercice structuraux pour faire pratiques les points de grammaire qu'on aborde avant de faire les exercices qu'on propose et qui sont généralement des exercices de traduction qui mêlent plusieurs points de grammaire dans une même phrase. 
Par exemple pour la section 8.5 ça pourrait être ce genre d'exercice : 
Dans les exemples on donne 
Johano lavis sin. / Johano lavis lin.

On pourrait proposer une exercice avec les phrases suivantes à compléter :

Maria manĝis ___ kukon. (Elle a mangé son propre gâteau.)
Maria manĝis ___ kukon. (Elle a mangé le gâteau qui était dans l'assiette de son mari.)
Maria manĝis ___ kukon. (Elle a mangé le gâteau qui était dans l'assiette de sa fille.)

Johano promenis kun —— hundo. (Il a promené son propre chien.)
Johano promenis kun —— hundo. (Il a promené le chien de son voisin.)
Johano promenis kun —— hundo. (Il a promené le chien de sa grand-mère.)

**Comment by emmrichard** [comment]
J'ai ajouté un exercice en tout premier pour les phrases sur les participes.

Il reste à ajouter un exercice sur sia et ŝia / lia
