### ISSUE TITLE
les leçons ne sont pas envoyés quand on attribue un élève de niveau 3 à un correcteur

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#375]

**Comment by axel584** [comment]
@emmrichard : je pense avoir corrigé, mais il faudrait réessayer... (et clôturer si ça fonctionne) c'est lié à la #259

**Comment by emmrichard** [comment]
J'ai toujours un problème avec la leçon 1.

1. Je crée un nouveau compte et je le valide
2. Avec ce compte, je fais la leçon 1 du cours de 2e niveau et j'envoie les exercices.
3. Avec mon compte admin, j'attribue un correcteur à cet élève.
--> Le correcteur devrait recevoir le premier devoir, mais ça ne fonctionne pas.

4. Avec le compte de l'élève je renvoie le premier devoir et cette fois, le mail part bien.

**Comment by axel584** [comment]
@emmrichard  : tu as le problème uniquement sur Gerda ou sur les autres cours ? Chaque cours est différent.

**Comment by emmrichard** [comment]
@axel584 : c'était avec le cours de 3e niveau

Je viens de refaire un test avec Gerda. La leçon 1 est bien envoyée, mais j'ai ce message d'erreur à l'écran, quand j'attribue un correcteur à l'élève : 
update nuna_kurso set nunleciono=01,stato='K',lastdato=CURDATE() where studanto=8063 and (stato='N' or stato='K') and kurso='GR'

**Comment by axel584** [comment]
@emmrichard : c'est bon j'ai corrigé. Mais il faut ajouter les deux colonnes avec la requête : 
`ALTER TABLE  eraraj_lecionoj ADD  leciono INT NULL , ADD  kurso VARCHAR( 2 ) NULL ;`
(la commande est dans changelog.sql au besoin)

**Comment by emmrichard** [comment]
J'ai testé sur le cours de niveau 3. c'est bon. Mais j'ai quand même ce message quand j'attribue le correcteur, sur la page administriNunanKurson.php : 
update nuna_kurso set nunleciono=01,stato='K',lastdato=CURDATE() where studanto=8064 and (stato='N' or stato='K') and kurso='3N'

@axel584  : Aurais-je oublié de faire quelque chose ?
