### ISSUE TITLE
[inscription] Blocage lors de l'inscription au DLEK

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#4]
Test d'inscription avec une adresse email erronée, et des réponses fausse.

J'ai ce message sur la page korekti.php :
Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /arthur/sites/ikurso-dev/util.php on line 18

Warning: fsockopen(): unable to connect to :25 (php_network_getaddresses: getaddrinfo failed: Name or service not known) in /arthur/sites/ikurso-dev/util.php on line 18

Warning: Cannot modify header information - headers already sent by (output started at /arthur/sites/ikurso-dev/util.php:18) in /arthur/sites/ikurso-dev/fr/korekti.php on line 283

**Comment by axel584** [comment]
C'est gênant ça, c'est justement le truc qui doit vérifier que l'on a bien une adresse valable... mais le but c'est que ça retourne une erreur propre ;-)

**Comment by axel584** [comment]
Est ce qu'une correction par une vérification en html5 du champ suffirait ?

**Comment by emmrichard** [comment]
Peut-être. Il me semble que c'est ce qui est fait dans le formulaire de contact de SPIP.

**Comment by axel584** [comment]
Est ce que tu as le même message quand tu envoies un message aux administrateurs ? (car ça devrait être la même fonction qui vérifie l'adresse email dans les deux cas)

**Comment by axel584** [comment]
C'est bizarre car en local, je n'ai pas de message d'erreur "dégueulasse", mais un beau message d'erreur quand je met une adresse invalide (testé sur l'inscription au "kurso de esperanto")

**Comment by axel584** [comment]
Peux tu réessayer sur les différentes inscriptions ainsi qu'à l'envoie d'un message aux administrateurs et me dire dans quel(s) cas ça pose problème ?

**Comment by emmrichard** [comment]
J'ai réussi à reproduire le cas en faisant une inscription à Gerda.
Sur ikurso-dev, je me suis inscrite avec un nouvel identifiant (voir capture), et page korekti s'est affichée avec le message suivant : 
Warning: mysql_select_db(): Access denied for user 'www-data'@'localhost' (using password: NO) in /arthur/sites/ikurso-dev/fr/korekti.php on line 203

Warning: mysql_select_db(): A link to the server could not be established in /arthur/sites/ikurso-dev/fr/korekti.php on line 203

Warning: mysql_query(): Access denied for user 'www-data'@'localhost' (using password: NO) in /arthur/sites/ikurso-dev/fr/korekti.php on line 204

Warning: mysql_query(): A link to the server could not be established in /arthur/sites/ikurso-dev/fr/korekti.php on line 204
INSERT : Invalid query :select * from personoj where enirnomo=''

![capture 2016-06-05 a 15 28 39](https://cloud.githubusercontent.com/assets/1328018/15805699/63c051ea-2b32-11e6-9601-a522f73e2354.jpg)

**Comment by emmrichard** [comment]
Le problème existe aussi en prod

**Comment by emmrichard** [comment]
Je vois. C'est parce que je n'ai pas coché la case "Je ne suis pas encore inscrit sur ce site". 
Il faudrait améliorer la présentation de la page, pour bien séparer les deux cas : sur un premier écran on propose le choix "j'ai déjà un compte", avec juste en-dessus le champ de saisie de l'identifiant et du mot de passe (comme actuellement), et le choix "je n'ai pas encore de compte". Ça serait seulement lorsqu'on clique sur ce choix qu'on arrive alors au formulaire de saisie de l'inscription.

**Comment by emmrichard** [comment]
Il y a aussi un autre problème : si on se trompe dans le formulaire, par exemple si on saisit deux mots de passe différentes, on revient alors sur la page du formulaire avec le message d'erreur "mots de passe identique", mais l'option "J'ai déjà un compte" redevient cochée, alors que c'est l'option "Je n'ai pas encore de compte" qui devrait être cochée puisque c'est celle-là qu'on avait choisie.

**Comment by emmrichard** [comment]
Voir ce qu'on fait si on est déjà connecté.

**Comment by axel584** [comment]
Le nouveau système est totalement différent, il ne devrait donc plus avoir ce soucis (car si l'adresse email est erronée, la personne ne peut pas créer de compte)
