### ISSUE TITLE
Statut incorrect pour l'élève qui a terminé

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#40]
Scenario :
1. L'élève envoie la leçon 10
2. Le correcteur indique que l'élève a terminé
--> Sur la page "Mes élèves", l'élève apparaît correctement dans l'onglet "Anciens élèves" avec comme dernière leçon indiquée, la dixième leçon.
3. Sur la page d'admin, l'élève apparaît dans la liste "Ont fini le cours", ce qui est correct, mais dans la fiche, il est dans indiqué comme un élève en attente de correcteur (voir capture).
![capture 2016-05-31 a 23 19 20](https://cloud.githubusercontent.com/assets/1328018/15690905/230d4158-2786-11e6-931b-b4200db6a866.jpg)

**Comment by axel584** [comment]
J'ai un peu de mal à savoir comment ça devrait fonctionner exactement car il y a normalement la possibilité d'attribuer à un élève un autre correcteur ou de lui attribuer un nouveau correcteur pour un autre cours.
En revanche, dans ton cas, ce qui est bizarre, c'est qu'on ne voit pas que l'élève a terminé le premier cours.

Donc, je ne suis pas sûr que ce soit un bug, je me demande si ce n'est pas une fonctionnalité qui permet d'attribuer à l'élève un nouveau correcteur...

Si on veut modifier ça, il faudrait réfléchir à comment gérer les cas suivants : 
- un élève a fini le cours en 10 leçons et veut s'inscrire à un autre cours (gerda ou ikurso) (avec le même correcteur ou un autre)
- un élève a fini le cours en 10 leçons il y a longtemps et veut le refaire (avec le même correcteur ou un autre)

**Comment by axel584** [comment]
Je vais fermer cette fiche pour le moment, on verra quand on aura installé la génération du diplome en PDF si c'est nécessaire d'améliorer les choses de ce côté là.
