### ISSUE TITLE
[GoodUI] : barrer les sections finies dans le sommaire

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#411]
http://goodui.org/#17 : montrer l'état d'avancement clairement : et si on barrait les noms des sections dans le sommaire ? (en plus de la coche)

**Comment by axel584** [comment]
Euh, ça ne fonctionne pas chez moi...

**Comment by emmrichard** [comment]
J'ai dû forcer la mise le rechargement de la page pour que le css modifié soit bien pris en compte.
Est-ce que tu peux vérifier si tu as bien ça en ligne 467 dans ikurso.css ?

> ul#enhavtabelo li.farita a {
> 	text-decoration: line-through;
> 	text-decoration-color: #2196F6;
> }
