### ISSUE TITLE
dispatcher les prépositions dans les premières leçons

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#431]
Evaluation de la leçon :6 (3/4) : Trop confus, trop de choses d'un coup c'est dommage que les choses ne soient pas plus progressives. Là c'était trop de prépositions d'un coup du coup pour les assimiler c'est bien plus compliqué que les anciennes leçons où le vocabulaire a été instillé petit à petit et du coup bien validé. Merci quand même pour le temps que vous passez sur ce projet

**Comment by emmrichard** [comment]
leçon 2 : antaŭ, sub, sur, super
leçon 3 : apud, ĉe, malantaŭ, al
