### ISSUE TITLE
ajouter une phrase de conseils pour les exercices de traduction

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#435]
Il est parfois nécessaire de s'éloigner du texte original pour que la traduction soit agréable à lire. Une bonne traduction est une phrase qui ne donne pas l'impression d'avoir été traduite.

**Comment by emmrichard** [comment]
l'idéal serait de ne plus avoir d'exercice de traduction...

**Comment by emmrichard** [comment]
Modification faire en base pour les exercices de traduction vers le français.
