### ISSUE TITLE
Faire une page "unique" pour chaque diplôme

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#438]
Faire en sorte que sur la page "diplôme" d'un élève, on puisse passer un paramètre unique (sa clef d'activation ?) pour pouvoir afficher cette page ailleurs et qu'on puisse y accéder même si on n'est pas connecté.

Sur cette page, on affichera : 
- un lien d'impression (comme actuellement)
- un lien pour diffuser l'information sur Facebook
- un lien pour revenir à ses données personnelles (si l'élève est connecté)
- un lien pour découvrir gratuitement ce cours (si l'élève n'est pas connecté)

**Comment by axel584** [comment]
https://korben.info/bouton-partage-twitter-facebook-sans-tracking.html

**Comment by axel584** [comment]
Attention, le diplôme s'affiche dans Facebook que si on passe par un lien qui contient déjà la clef "aktivigo"... Il faut la chercher dans l'autre cas

**Comment by axel584** [comment]
@emmrichard : qu'en dis tu ? As tu fait quelques tests ?

**Comment by emmrichard** [comment]
@axel584 : qu'est-ce que tu entends par "aktivigo" ? J'ai fait le test en cliquant sur le lien dans la page Données personnelles, et j'ai juste "localhost" dans la prévisualisation de Facebook, et quand je publie sur mon mur, j'ai une erreur "Cette fonctionnalité n’est pas disponible.: Une erreur s’est produite lors du traitement de cette demande. Veuillez réessayer plus tard."

**Comment by axel584** [comment]
@emmrichard : il s'agit juste d'une variable dans l'url. Par exemple : 
http://82.239.0.181/ikurso/diplomeImage.php?kurso=GR&clef=ee9dace9b97ee14f17f2c2969c77d2c6

tu vois bien qu'il y a "clef" qui est passé dans l'url et ça correspond à un numéro unique qui permet de savoir de quel élève il s'agit.

Pour ton histoire de localhost, il faut vérifier que dans ton fichier config.php tu as bien l'url avec une adresse ip et pas avec ton localhost (qui peut aussi être 127.0.0.1). Par exemple, moi j'ai : 
$urlracine = "http://82.239.0.181/ikurso/";

Au besoin, tu peux trouver ton adresse ip externe ici : http://www.mon-ip.com/

**Comment by emmrichard** [comment]
@axel584 : je n'ai pas réussi avec l'IP (ça me renvoie sur la livebox, j'arrête de chercher pour aujourd'hui), mais j'ai essayé sur ta machine, et c'est bon.
