### ISSUE TITLE
Faire une page statistique élève

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#447]
Mettre dans cette table : 

- le classement des meilleurs élèves #434 
- le nombre de mots par force pour l'élève en question #421 
- l'évolution de l'élève par rapport aux autres #247 
- la liste des mots "difficiles" (à faire plus tard quand on aura un historique des mots échoués)

Dans cette page, seul le premier élément n'est pas dépendant de l'élève et peut être affiché si l'élève n'est pas connecté.
Cette page doit pouvoir être atteinte en indiquant la clef d'activation de l'élève en paramètre pour pouvoir accéder aux données d'un autre élève.
Si la clef d'activation est passé en paramètre, on affiche le pseudo de l'élève dans le titre ("statistiques de X" au lieu de "statistiques") 

On affichera (ensuite ?) un lien pour faire connaître cette page sur Facebook

**Comment by axel584** [comment]
@emmrichard : j'ai fait la page statistikoj.php (pas encore relié aux autres pages), j'ai mis un menu du style "sommaire" que l'on a sur les leçons, mais il s'affiche en dessous de la page. Je me demande si tu peux corriger ça ?

**Comment by emmrichard** [comment]
@axel584 : j'ai fait la modif dans la page pour afficher le sommaire dans la marge, comme dans les pages de leçons. Peux-tu me voir si ça te convient ? Si oui, tu pourras fermer cette issue.
