### ISSUE TITLE
[aide] Faire un mode d'emploi pour "Kurso de esperanto"

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#45]
Avec capture d'écran pour expliquer comment envoyer ses messages à son correcteur.

**Comment by emmrichard** [comment]
J'ai modifié la page aligxi pour expliquer comment faire.

**Comment by emmrichard** [comment]
J'ai aussi mis ça dans un document. Je n'ai pas expliqué dans le détail comment utiliser toutes les fonctionnalités du logiciel (par exemple, les accents), mais est-ce bien utile ?
[ikurso-aide.pdf](https://github.com/axel584/ikurso/files/299450/ikurso-aide.pdf)
