### ISSUE TITLE
Problème de renvoi vers une nouvelle leçon

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#458]
Concernant le cours, effectivement, tout a été formaté, à l'exception des petits exercices de vocabulaire qui, une fois terminés, me renvoient à la leçon 7.

**Comment by axel584** [comment]
@emmrichard : je ne comprends pas de quoi il s'agit...

**Comment by emmrichard** [comment]
@axel584 : moi non plus :-)
Il faudrait retrouver la remarque de l'élève pour comprendre de quoi il s'agit.

**Comment by emmrichard** [comment]
On va dire que comme on ne voit pas le problème, il n'y en a pas :-)
