### ISSUE TITLE
Préciser sens de kiu et kio 

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#477]
kiu : objet ou personne identifié et kio : chose en générale, non identifié...

page 21 ????

**Comment by axel584** [comment]
@emmrichard : Il s'agit du fichier PDF, je serais d'avis de le repousser à plus tard...
On pourrait aussi ajouter un exemple : 
- kiu libro estas via ? 
- kio estas tio ?

Peut être aussi spécifier qu'on ne met JAMAIS "kio" s'il est suivi d'un nom en -o

A voir aussi si dans le cours, on ne devrait pas ajouter une exercice spécifique pour trouver le bon mot entre les deux propositions

**Comment by emmrichard** [comment]
Voir aussi #550
