### ISSUE TITLE
[inscription] Aucun message affiché en cas d'erreur dans le QCM de DLEK

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#5]
Cas testé : Inscription avec des données personnelles correctes, mais des réponses fausses.

La page fr/cge/lec01.php?erarkodo=2?erarkodo=13&noto=1/13 s'affiche, mais aucun message d'erreur n'est affiché.

**Comment by emmrichard** [comment]
note : isobug

**Comment by axel584** [comment]
En fait, le problème c'est que quand on revient plusieurs fois sur la même page, les "erarkodo" s'ajoutent ici, dans ton url, tu as un erarkodo à 2 (=champ obligatoire manquant) et à 13 (=QCM KO)
Donc, c'est quand même un vrai bug :-)

**Comment by axel584** [comment]
j'ai corrigé le problème (qui multiplie les paramètres dans l'url)

**Comment by axel584** [comment]
@emmrichard : ajouter les styles CSS pour afficher les questions en erreur
@axel584 : utilise le style pour montrer les erreurs dans le QCM

**Comment by axel584** [comment]
cette issue est un doublon de la #12
