### ISSUE TITLE
[suivi des élèves] Envoyer un message automatique aux correcteurs qui ont des élèves sans action depuis 30 jours

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#50]
un message du style : 

Object : vos élèves ont besoin de vous !

Saluton,
nous avons remarqué que certains de vos élèves n'ont pas envoyé de leçon depuis plus de 30 jours, il s'agit de : 
Coxinel n'a pas envoyé de leçon depuis 42 jours
Roger n'a pas envoyé de leçon depuis 35 jours

Un petit message gentil de votre part les aidera sans doute à se remotiver pour continuer leur apprentissage. Néanmoins, si l'élève ne souhaite plus continuer le cours, vous pouvez indiquer que cet élève a abandonné dans le menu "Mes élèves", ainsi vous pourrez recevoir un nouvel élève à la place. Ne le prenez pas comme un échec personnel, seulement 20% des élèves qui ont commencé le cours vont jusqu'au bout, mais ce nombre peut être améliorer en créant une relation amicale entre l'élève et le correcteur.

Bon courage,

Ikurso

**Comment by axel584** [comment]
Peut être pas très urgent car il risque d'avoir beaucoup de correcteurs qui ne donnent plus signe de vie et c'est peut être mieux de ne pas leur permettre de faire de la place pour de nouveaux élèves

**Comment by emmrichard** [comment]
Dans ce cas-là, l'idéal serait qu'en même temps qu'on met l'élève à "abandonné", on décrémente le nombre de places disponibles pour ce correcteur. Reste à voir comment on pourrait détecter les cas où ça vaut mieux de faire comme ça.

**Comment by axel584** [comment]
L'idée initiale était d'envoyer un mail aux correcteurs pour que les correcteurs mettent les élèves en "a abandonné"... après, si on les mets nous même en "a abandonné", c'est peut être différent.
Il faudrait peut être regarder les correcteurs qui n'ont pas reçu de nouveaux élèves depuis un an et qui n'ont mis aucun de leurs élèves en "a abandonné" (de toutes façons, s'ils n'ont pas eu de nouveaux élèves depuis un an, c'est qu'ils ne se sont pas occupés de leurs élèves)

**Comment by axel584** [comment]
@emmrichard : et je pense qu'il faudrait envoyer ce message uniquement une fois par mois pour ne pas flooder les correcteurs.
