### ISSUE TITLE
simplifier les questions 6.15

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#513]
Sur la page : 
http://ikurso.esperanto-france.org/fr/cge/lec06.php?section=15

Il y a des phrases complexes avec des nouveaux mots. Par exemple : 
Faru vian aferon, Dio zorgos PRI la cetero.

"Fari" est expliqué entre parenthèse, mais je crois que "dio", "zorgi" et "cetero" n'est pas expliqué...

Dans la phrase suivante, "ferii" n'est pas expliqué.

**Comment by emmrichard** [comment]
fait en v19
