### ISSUE TITLE
Exercice 6.12 (DLEK) problème pour écrire en français

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#518]
Dans l'exercice 3, on demande d'écrire une phrase en espéranto, puis de la traduire. Dans ce qu'on écrit en français, ça pose un petit problème : 
![screenshot 2017-02-15 a 17 49 07](https://cloud.githubusercontent.com/assets/1328018/22984887/19e935bc-f3a7-11e6-8a6e-dadafe517bda.png)

Pour résoudre, ce problème, on pourrait scinder l'exercice en 2 : premier exercice, on écrit les phrases en espéranto, deuxième exercice, on demande de traduire.

@axel584 : qu'en dis-tu ?

**Comment by axel584** [comment]
Oui j'avais pensé à la même chose

**Comment by emmrichard** [comment]
Doublon avec #806
