### ISSUE TITLE
expliquer que kio n'est jamais suivi d'un nom

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#550]
Sur la page : 
http://ikurso.esperanto-france.org/fr/cge/lec03.php?section=12

après : 

> REMARQUE : Comme kio se réfère à quelque chose d’indéfini, il ne prend jamais la marque du pluriel.

Préciser : 
REMARQUE : Comme kio se réfère à quelque chose d’indéfini, il ne prend jamais la marque du pluriel. De même, il n'est jamais suivi par un nom en -o.

Exemple :
Kio estas tio ? Qu'est ce que c'est ?
Mais
Kiu libro estas via ? Quel livres est le tiens

**Comment by emmrichard** [comment]
voir aussi #477
