### ISSUE TITLE
préciser le fonctionnement de la négation

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#552]
Evaluation de la leçon :2 (5/3) : Bonjour, Je trouve qu'il pourrait être pas mal de préciser en 2.7 (la forme négative) le rapprochement que j'ai deviné entre "Cxiam" et "Neniam" ; "Kiu" et "niniu" ; "kie" et "nenie" ; et enfin "kio" et "nenio". ça m'a beaucoup aidé pour les retenir puisque je viens de les découvrir et ne les ai lu qu'une fois. Cordialement, Maïeul

**Comment by emmrichard** [comment]
À ce niveau du cours, on a juste vu "kiu" et "kie" dans la leçon 1, et on aborde de nouveau kiu et kio dans la leçon 3.
ĉiam n'est introduit que dans la leçon 5
