### ISSUE TITLE
Affichage des caractères spéciaux dans la fiche d'un élève

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#6]
\ dans le commentaire de l'élève dans sa fiche
![capture 2016-05-29 a 22 08 17](https://cloud.githubusercontent.com/assets/1328018/15635821/12ae1082-25ea-11e6-8886-ed207631e227.jpg)

**Comment by axel584** [comment]
Tu as fait ça à l'inscription ? Car j'ai essayé de le faire à la mise à jour des données personnelles et ça fonctionnait bien.

**Comment by emmrichard** [comment]
Oui, c'est le commentaire que j'avais mis lors de l'inscription.

**Comment by emmrichard** [comment]
Encore quelques petits problèmes avec les accents.
Voir par exemple la fiche n° 2278
![capture 2016-05-31 a 22 19 36](https://cloud.githubusercontent.com/assets/1328018/15689184/17057090-277e-11e6-86b0-270033a4e164.jpg)

**Comment by emmrichard** [comment]
Ça semble être un exemple isolé, donc je pense qu'on peut corriger en base.

**Comment by axel584** [comment]
Je pense que c'est plusieurs exemples isolés (j'ai remarqué des problèmes sur les anciennes fiches...)
En fait, le problème est dû au fait qu'en base, c'est écrit comme ça, mais qu'on avait du code qui "corrigeait" les problèmes... Et comme c'était converti dans un encodage tout pourri en base et décoder pour afficher de l'utf-8 après, on ne voyait pas trop le problème...

**Comment by axel584** [comment]
Du coup, je ferme cette issue
