### ISSUE TITLE
Le filtrage par date dans stirpanelo ne fonctionne pas

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#616]
Par exemple : si je filtre en indiquant des dates, j'ai toujours uniquement les plus récents. Si, en plus des date, je sélectionne un type de log, j'ai la même chose (logs les plus récents toutes rubriques confondues)

**Comment by axel584** [comment]
@emmrichard  : Je n'arrive même pas à ouvrir l'outil pour sélectionner une date. Peut être qu'on pourrait utiliser le champ date comme tu l'as fait pour la date de naissance ?

**Comment by axel584** [comment]
C'est corrigé en utilisant l'outil de date du html5 (à la place du DataPicker de MaterializeCSS)
