### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by MichelJeanPaul** [axel584/ikurso#619]
Warning: Cannot modify header information - headers already sent by (output started at /arthur/sites/ikurso/statistikoj.php:1) in /arthur/sites/ikurso/statistikoj.php on line 6

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1' in /arthur/sites/ikurso/db.inc.php:103 Stack trace: #0 /arthur/sites/ikurso/db.inc.php(103): PDO->query('select * from p...') #1 /arthur/sites/ikurso/statistikoj.php(7): apartigiPersonon(NULL) #2 {main} thrown in /arthur/sites/ikurso/db.inc.php on line 103

**Comment by axel584** [comment]
Salut Michel,
Peux tu nous expliquer comment tu es arrivé sur cette page pour voir cette erreur ?

Merci à toi,

Axel

**Comment by MichelJeanPaul** [comment]
salut,

Il faut dire que je commence à essayer de faire l'organigramme pour
comprendre comment cela marche et j'essaye de repérer les programmes dans
l'URL
Probablement il faudra que je m'inscrive, mais pour le moment, je ne suis
pas décidé de faire l'effort d'apprendre. J'attends qu'Eva soit à l'aise
pour avoir mon prof particulier à domicile.

J'ai commencé par :
http://ikurso.esperanto-france.org/   adresse donnée par wikipédia
Là, j'ai choisi "quoi de neuf"
sur l'annonce

>
>    - version 13. Mars 2017
>    -
>
>    Possibilité d'imprimer les leçons.
>
>    Ajout d’outils statistiques
>    <http://ikurso.esperanto-france.org/statistikoj.php>.
>
> cela m'a entrainé sur la page d'erreur à la page

http://ikurso.esperanto-france.org/statistikoj.php

Probablement une petite faute de frappe.
Amitiés

Michel




2017-05-08 21:20 GMT+02:00 axel584 <notifications@github.com>:

**Comment by axel584** [comment]
Doublon avec #594

**Comment by MichelJeanPaul** [comment]
Salut
J'ai vu un peu plus tard, la correction est très facile une fois qu'on a
assimilé les variables et les programmes.
"if ($connected)  ..... à placer avant l'instruction de direction et
éventuellement avoir comme variable globale $connected false jusqu'à la
connexion.



2017-05-09 22:37 GMT+02:00 axel584 <notifications@github.com>:

**Comment by axel584** [comment]
corrigé dans la prochaine version
