### ISSUE TITLE
Ajouter une information sur les données personnelles pour inciter les élèves à rentrer leur code postal

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#621]
Un truc du style : "En renseignant votre pays et votre code postal, nous pourrons, si cela est possible, vous attribuer un correcteur qui habite près de chez vous"

Et bien sûr, évaluer si cette mention augmente ou diminue le nombre de personnes qui rentrent leur code postal.

**Comment by emmrichard** [comment]
doublon avec la #642
