### ISSUE TITLE
Rendre la FAQ plus accessible

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#626]
Plutôt que d'avoir le terme "Foire aux questions" qui ne contient pratiquement que des informations sur les clavier en espéranto, il serait préférable d'avoir un menu "Informations pratiques" qui contiendrait 4 entrées : 
- comment s'inscrire ? (on pourrait ajouter un truc pour que les élèves puissent choisir un correcteur)
- comment suivre le cours (avec des conseils sur l'ordre des sections, des leçons, l'outil de révision du vocabulaire etc.)
- comment écrire en espéranto (avec ce qu'on a actuellement dans FAQ)
- Que faire après le cours ?
- comment devenir correcteur ?
- comment nous aider ? (à fusionner avec comment devenir correcteur ?)
Parler du fait que l'on recherche des informaticiens et des enseignants. Que l'on peut adhérer à l'association pour nous soutenir.

**Comment by emmrichard** [comment]
Reste à faire : 
- comment nous aider ? (à fusionner avec comment devenir correcteur ?)
Parler du fait que l'on recherche des informaticiens et des enseignants. Que l'on peut adhérer à l'association pour nous soutenir.
- continuer d'enrichir la page sur comment suivre le cours (avec des conseils sur l'ordre des sections, des leçons, l'outil de révision du vocabulaire etc.)
