### ISSUE TITLE
passer en https

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#657]
Il me semblerait judicieux de sécuriser (https) au moins la création de compte et l'ouverture de session.

réponse de SEB : 
actuellement le SSL est fonctionnel,
mais le certificat valide seulement pour esperanto-france.org

pour les sous-domaines je pensais être obligé de changer l'archcitecture en passant par un module Node plutôt que par le script certbot,
mais avec les SAN il y a peut-être moyen de faire plus simple :
https://en.wikipedia.org/wiki/Subject_Alternative_Name
https://letsencrypt.org/docs/faq/

n'hésite pas à m'en reparler après le 18 juin :)

**Comment by emmrichard** [comment]
@axel584 : tout est bon ?
