### ISSUE TITLE
[attestation] Envoyer un  mail à l'élève qui a fini un cours

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#67]

**Comment by emmrichard** [comment]
J'ai ajouté les templates des mails à envoyer à l'élève qui a terminé, pour leur dire de télécharger l'attestation. Il y en a un pour chaque cours : 
finiStuCGFR.html
finiStuKEFR.html
finiStuCGGE.html

**Comment by axel584** [comment]
retirer "FR" dans le nom du mail
