### ISSUE TITLE
Modifier le message envoyé pour activer son compte

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#671]
mettre un message plus explicite.
Je pense qu'il faut juste "montrer le lien". On pourrait transformer : 

`<p>Afin de valider votre inscription, il vous suffit de cliquer sur le <a href="##LIEN_ACTIVATION##">lien d'activation de votre compte</a>.</p>`

en

`<p>Afin de valider votre inscription, il vous suffit de cliquer sur le <a href="##LIEN_ACTIVATION##">lien d'activation de votre compte</a> :<br/><a href="##LIEN_ACTIVATION##">##LIEN_ACTIVATION##</a> </p>`

Du coup, ça donnerait un truc du style : 
Afin de valider votre inscription, il vous suffit de cliquer sur le **lien d'activation de votre compte** :
**ikurso.esperanto-jeunes.org/aktivigi.php?clef=XXX546qdf**

Qu'en dis tu ?

Au début, j'avais pensé ajouter un paramètre différent pour savoir si les élèves cliquent sur le texte ou sur l'url, mais c'est peut être s'embêter pour rien.

**Comment by axel584** [comment]
Voilà ce que ça donne : 
![image](https://user-images.githubusercontent.com/1334088/27195850-a279d804-5208-11e7-91ab-29e2cfcd1f7b.png)
