### ISSUE TITLE
Problème encodage mail de confirmation d'inscription envoyé à l'élève

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#7]
Cas testé : réception du mail de l'élève dans Thunderbird

L'encodage du texte semble correct 
![encodage](https://cloud.githubusercontent.com/assets/1328018/15635977/db94767a-25f0-11e6-9542-4402d745ee42.jpg)

mais le contenu n'apparaît pas correctement 
![message](https://cloud.githubusercontent.com/assets/1328018/15635978/f5bf12c6-25f0-11e6-99d6-0194dafd51d6.jpg)

**Comment by emmrichard** [comment]
Remarque : le message suivant (donnant les coordonnées du correcteur à l'élève) s'affiche correctement

**Comment by axel584** [comment]
Les mails sont dans le répertoire "mails" de github, je pense qu'il faudrait mettre les entités html correspondante... C'est le genre de truc que je peux faire par l'interface de git.

**Comment by emmrichard** [comment]
Dans le cas cité, je pense que le modèle est aligxiCGFR.html et il est en charset=iso-8859-1
Je vais le passer en utf-8 et tester si ça corrige le problème (qui doit aussi exister en prod)

**Comment by emmrichard** [comment]
corrigé

**Comment by emmrichard** [comment]
J'ai vérifié l'encodage des mails.
J'en ai profité pour supprimer la référence au forum, et j'ai ajouté la signature quand elle manquait
