### ISSUE TITLE
Remplacer les | par des sauts de ligne dans la page korektado

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#710]

**Comment by axel584** [comment]
@emmrichard : euh, normalement y'a pas de traits verticaux sur cette page car elle n'affiche que le champ "respondo" de la table "ekzerceroj" et c'est le champ "normaligita" qui contient les traits verticaux.
En gros, il y a "une réponse type" (comme on pourrait avoir une rédaction type à une dissert de philo), mais plusieurs réponses différentes peuvent être automatiquement acceptées.

**Comment by emmrichard** [comment]
@axel584 : en principe, oui, mais il y a des cas où plusieurs réponses se valent et je pense que ce serait mieux de les mettre au même plan dans le corrigé-type. 
Par exemple, dans le premier chapitre de Gerda, on doit faire une phrase avec { al -as -in- ir- knab- li -o }
On peut très bien avoir comme réponses "Li iras al knabino" et "Knabino iras al li". Et la 2e réponse n'est pas une variante de la première. Ce sont deux réponses qui se valent, et je ne vois pas de raison d'en privilégier une. 
L'idée n'est pas de mettre autant de réponse dans le champ "respondo" quand dans le champ "normaligita", mais dans certains cas comme celui ci-dessus.
