### ISSUE TITLE
Faire une icone pour l'application android

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#764]
+ modifier le nom de l'executable pour l'appeler ikurso

voir documentation ici : 
https://cordova.apache.org/docs/fr/latest/config_ref/images.html

Mettre les icones dans le répertoire : /ikurso/ikurso/res/icon/

et changer le fichier config.xml pour ajotuer : 

```
   <platform name="android">
               <icon src="res/android/ldpi.png" density="ldpi" />
               <icon src="res/android/mdpi.png" density="mdpi" />
               <icon src="res/android/hdpi.png" density="hdpi" />
               <icon src="res/android/xhdpi.png" density="xhdpi" />
      </platform>
```

Il faut avoir les formats suivants : 
48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)
512 × 512 (Google Play store).png 

et dans le repertoire bildoj, on a déjà : 
  | touch-icon-60.png | 2017-09-19 08:12 | 1.5K |  
  | touch-icon-76.png | 2017-09-19 08:12 | 1.8K |  
  | touch-icon-120.png | 2017-09-19 08:12 | 4.3K |  
  | touch-icon-152.png | 2017-09-19 08:12 | 5.9K |  
  | touch-icon-167.png | 2017-09-19 08:12 | 6.3K |  
  | touch-icon-180.png | 2017-09-19 08:12 | 7.1K

**Comment by emmrichard** [comment]
J'ai mis aussi l'image en 512 dans le même dossier que les icônes.
