### ISSUE TITLE
Pays manquants dans la liste des pays 

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#773]
Il manque entre autres la Lituanie et d'autres pays dans les L
A vérifier dans la page perso et dans administri

**Comment by axel584** [comment]
Il n'y a pas tous les pays, c'est tout à fait normal. On peut les ajouter au fur et à mesure des besoins, mais ça ne sert à rien de faire une liste de 200 noms de pays alors que les 4 plus importants représentent 99% des inscriptions
