### ISSUE TITLE
Erreur à la connexion avec un compte élève

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#8]
Cas testé : j'étais connectée en admin. Je me déconnecte, puis je me reconnecter avec un compte élève.
Et là, c'est le drame !

Je me retrouve sur cette page : 
http://ikurso-dev.esperanto-jeunes.org/forum/index.php?sid=.php

avec cette erreur :
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)' in /arthur/sites/ikurso-dev/db.inc.php:9 Stack trace: #0 /arthur/sites/ikurso-dev/db.inc.php(9): PDO->__construct('mysql:host=loca...', NULL, NULL) #1 /arthur/sites/ikurso-dev/forum/common.php(132): malfermiDatumbazon() #2 /arthur/sites/ikurso-dev/forum/index.php(26): include('/arthur/sites/i...') #3 {main} thrown in /arthur/sites/ikurso-dev/db.inc.php on line 9

**Comment by emmrichard** [comment]
J'ai pu reproduire le cas.
Et lorsque je suis sur la page citée plus haut, si je vais directement sur la page d'accueil du site, elle apparaît normalement et moi, je suis correctement connectée avec le compte de l'élève que j'avais utilisé.

**Comment by axel584** [comment]
C'est pas isobug, mais c'est pas mieux actuellement, on arrive sur la page du forum qui ressemble à ça : 
![image](https://cloud.githubusercontent.com/assets/1334088/15655839/16e8b6b8-26a1-11e6-9fe8-98dfb70fd8c8.png)

Je suis surpris que personne ne l'ait signalé...

Bref, il ne faudrait pas tarder à mettre en ligne la version de dev :-)
