### ISSUE TITLE
accepter le ù à la place de ux dans les réponses

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#802]
et le convertir automatiquement à la saisie

A voir le mécanisme qui permet de convertir les x en chapeau

**Comment by mcorne** [comment]
dans le fichier xAlUtf8.js, il suffit d'ajouter le u accentué lignes 8 et 14

avant
```js
    t = t.replace(/u[xX]/g, "\u016d");
    ...
    t = t.replace(/U[xX]/g, "\u016c");
```
après
```js
    t = t.replace(/(u[xX]|ù)/g, "\u016d");
    ...
    t = t.replace(/(U[xX]|Ù)/g, "\u016c");
```
