### ISSUE TITLE
Sur la page reago, préremplir le champ adresse email

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#86]
si l'élève est déjà connecté
Et si l'élève a déjà un correcteur, le mettre en copie

**Comment by emmrichard** [comment]
@axel584 : est-ce bien nécessaire de mettre le correcteur en copie ? Peut-être que l'élève souhaite justement nous contacter sans que son correcteur soit en copie.

**Comment by axel584** [comment]
Super. Disons qu'historiquement, on avait souvent des messages où je devais chercher l'adresse du correcteur pour le mettre en copie.
A l'inverse, je ne me souviens pas d'avoir reçu de messages où l'élève se plaignait de son correcteur et ne voulait pas qu'il soit au courant de son message...

Bref, d'un point de vue empirique, ça ne me semble pas poser problème si le correcteur reçoit une copie du message adressé par l'élève... Mais ce n'est pas non plus indispensable.

**Comment by emmrichard** [comment]
Pour que ce soit plus clair, on pourrait dans ce cas indiquer "Votre message sera envoyé aux administrateurs du cours et à votre correcteur." ?

**Comment by axel584** [comment]
On ne va pas s'embêter pour le moment, on verra dans quelques temps si on reçoit encore beaucoup de messages d'élèves dans ce sens.
