### ISSUE TITLE
Faire un TU avec Sélénium 

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#87]
Faire un truc minimaliste, mais qui serve de cadre pour les tests ultérieur, par exemple, un utilisateur qui s'inscrit créer son compte.

Gérer les "prérequis" (action que l'on fait avant le test - insertion de données en base par exemple)
Gérer les vérifications 
Gérer les actions à faire après le test (nettoyage de la base par exemple)

**Comment by meunx** [comment]
Première livraison :
 - un module Python (SQLtest.py) contenant des fonctions pour initialiser les bases SQL ('personoj' et 'nuna_kurso' pour l'iinstant), faire une requête sur une des bases SQL, et vider les bases (encore 'personoj' et 'nuna_kurso'),
 - un script Python (Inscription.py) qui initialises les bases, crée une boite mail temporaire (via mailinator), l'utilise pour créer un compte Ikurso, va ouvrir le mail d'activation et suit le lien d'activation, rempli les champs "nom" et "prénoms", vérifie la nouvelle ligne associée au nouveau compte dans la base SQL, revient à la page d'accueil Ikurso pour vérifier le refus de création de compte sur une adresse e-mail ou un identifiant déjà en base, et enfin, qui vide les bases 'personoj' et 'nuna_kurso'.

Je n'ai pas l'habitude, ni d'Ikurso, ni de faire des tests automatisé. Mon premier jet est donc probablement très perfectible. N'hésitez pas à faire des remarques.
N'hésitez pas non plus à me poser des questions, si ça peut être utile une compréhension plus rapide, ou pour lever des ambiguïtés.

Pour info, les comptes utilisateurs crées lors de l'initialisation du test ont tous pour mot de passe "passwd".
Plus d'information dans les quelques commentaires du code Python.

**Comment by meunx** [comment]
Scripts de test en Python modifiés pour compatibilité Python 3 et Python 2 (testés Python 2.7 et Python 3.5).
Info : pour installer Selenium pour Python 3 : "pip3 install selenium" au lieu de "pip install selenium" pour Python 2
Info2 : le connecteur Python-MySQL utilisé est maintenant python-mysql.connector (python3-mysql.connector pour Python 3). Installation classique sous Ubuntu (apt-get install python3-mysql.connector).

**Comment by axel584** [comment]
@meunx : et tu arrives à faire tourner en parallèle les deux versions de python ?

**Comment by meunx** [comment]
Oui, par défaut j'ai Python 2.7, et j'ai aussi installé Python 3.5.

J'utilise la commande "python" (ou "python2) pour Python 2, et "python3" 
pour Python 3. C'est aussi simple que ça.

Par contre il faut penser à faire des installations en double.
Par exemple, pour l'installeur python "pip", il faut une installation 
pour python2 (apt-get install python-pip), et une pour python2 (apt-get 
install python3-pip)

Idem pour les installations via pip : "pip" pour pyhton2, et "pip3" pour 
python3.

**Comment by axel584** [comment]
Merci pour les infos, j'espère que cela me permettra de faire fonctionner ton script. Je te tiens au courant !

**Comment by axel584** [comment]
ça fonctionne très bien chez moi... Il va maintenant falloir créer une liste de scénario à tester
