### ISSUE TITLE
Empêcher la suggestion automatique pour le champ de formulaire de l'outil de révision des mots

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#874]
Firefox enregistre chez moi automatiquement des suggestions pour chaque entrée de formulaire, et d’une façon très étrange, non seulement il en a apparemment enregistré pour celui de révision de vocabulaire, mais en plus celles-ci changent à chaque question (pour être *systématiquement* fausses évidemment) ! J’ignore pourquoi, mais je crois savoir qu’il y a des attributs text input qui permettent d’éviter l’enregistrement de suggestions… et puis il doit y avoir quelque chose qui cloche pour que la suggestion change à chaque fois (alors qu’il ne devrait pas y en avoir du tout).

**Comment by emmrichard** [comment]
https://www.w3schools.com/tags/att_input_autocomplete.asp

Si ça ce marche pas, vider le cache, les cookies, etc. (la balle est dans le camp de l'utilisateur)
