### ISSUE TITLE
Le vocabulaire de Ikurso sur Anki

### ISSUE THREAD

**Issue by RomainTT** [axel584/ikurso#899]
Bonjour à tous,

Pour réviser le vocabulaire de Ikurso, je me suis créé un paquet de cartes à réviser sur l’application [Anki](https://apps.ankiweb.net/) (il s’agit d’un ensemble de logiciel très pratique pour mémoriser des choses).

Ce que j’ai fait, c’est copier le [vocabulaire](https://ikurso.esperanto-france.org/fr/cge/vocabula.php) du cours en 10 leçons, le nettoyer, et créer un fichier au format Anki.

Voici le [lien de téléchargement](https://ankiweb.net/shared/info/281835874) du paquet. Je me disais que vous auriez peut-être envie de mettre ce lien sur [la page des documents à télécharger](https://ikurso.esperanto-france.org/fr/elsxutoj.php).

**Comment by emmrichard** [comment]
à mettre dans la partie Logiciels tiers

**Comment by RomainTT** [comment]
Ah, je viens de m’apercevoir que le lien est détruit s’il n’y a pas beaucoup de téléchargements. J’ai donc re-partagé le paquet : https://ankiweb.net/shared/info/128564995

Ça signifie qu’il faudrait donc exporter le paquet, et l’héberger sur le site de Ikurso directement, pour éviter les disparitions impromptues…
