### ISSUE TITLE
Erreur lors de l'envoi d'une leçon

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#9]
Cas de test : leçon 3 de DELK, en n'étant pas identifié

Je remplis quelques exercices, j'indique mon identifiant et un mot de passe erroné. Le site me dit qu'il faut que je m'identifie en haut à gauche (il faudra améliorer ça, mais ce n'est pas le propos ici).
Je corrige en mettant un mot de passe correct, et là, j'obtiens cette erreur :

Warning: mysql_select_db(): Access denied for user 'www-data'@'localhost' (using password: NO) in /arthur/sites/ikurso-dev/fr/korekti.php on line 192

Warning: mysql_select_db(): A link to the server could not be established in /arthur/sites/ikurso-dev/fr/korekti.php on line 192

Warning: mysql_query(): Access denied for user 'www-data'@'localhost' (using password: NO) in /arthur/sites/ikurso-dev/fr/korekti.php on line 193

Warning: mysql_query(): A link to the server could not be established in /arthur/sites/ikurso-dev/fr/korekti.php on line 193
INSERT : Invalid query :select * from personoj where enirnomo='coxinel'

**Comment by axel584** [comment]
Je n'arrive pas à reproduire ton problème car quand je ne suis pas identifié, je ne peux pas remplir des exercices (j'ai une pop-up javascript quand je clique dans un champ formulaire qui me dit "identifez vous en haut à droite pour remplir les exercices" (il faudrait corriger pour mettre en haut à **gauche**)

Le problème serait plutôt qu'il permet de saisir son identifiant et son mot de passe à la fin de l'exercice... Si on veut à terme séparer l'inscription et les exercices, il faudrait aussi qu'on ne puisse s'identifier que par le menu en haut à gauche et que la zone d'exercices ne serve pas à gérer la connection

**Comment by emmrichard** [comment]
Oui, effectivement, c'est bien là le problème. Pour l'instant c'est isobug.

**Comment by axel584** [comment]
Retirer le layus en bas de la page, retirer également les champs identifiant/mot de passe car il n'y a que quand on est inscrit que l'on peut valider le formulaire.
