### ISSUE TITLE
Corriger le bug à l'inscription si l'utilisateur met un # dans son mot de passe

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#916]

**Comment by emmrichard** [comment]
Lors de la saisie du nouveau mot de passe, s'il contient un des caractères suivants, rien ne se passe (pas de retour, pas d'affichage de message d'erreur, et le bouton devient grisé) :
#

Si le mot de passe contient un des caractères suivants, on obtient le message "erreur interne" lors de la validation : 
'

Les mots de passe contenant un des caractères suivants sont acceptés, mais ensuite le mot de passe n'est pas reconnu (message en rouge "mot de passe incorrect" : 
!
?
&
-
_
#


Les caractères suivants sont utilisables dans un mot de passe : 
@  
"
