### ISSUE TITLE
Corriger le sommaire du DLEK

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#92]
Notamment 
9.3. Quelques adverbes primaires en -aux
9.4. Divers mots en -aux
dans fr/cge/enhavo.php

**Comment by emmrichard** [comment]
La page enhavo.php n'est accessible de nulle part.
Faut-il ajouter un lien vers cette page dans la page d'introduction ?
Et ensuite, depuis quelle page pourrait-on y accéder ? Peut-être ajouter une page "index" accessible depuis la liste des leçons qui est en haut de la page ? 
@axel584 : qu'en penses-tu ?
(si on la garde, je corrigerai la mise en page)

**Comment by axel584** [comment]
@emmrichard  : une idée comme ça, on pourrait mettre les deux pages dans la même page : 
http://ikurso.esperanto-france.org/fr/cge/enhavo.php
http://ikurso.esperanto-france.org/fr/cge/temaro.php

En cliquant sur "index", on arriverait sur l'index thématique et on aurait un onglet (ou un petit menu dans la colonne de droite) qui permettrait d'arriver sur la table des matières)

Je pense que ce serait bien que les deux soient dans le même fichier php pour ne pas oublier de mettre à jour l'un quand on met à jour l'autre. Qu'en dis tu ?

**Comment by emmrichard** [comment]
déjà fait
