### ISSUE TITLE
bug sur le vocabulaire

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#929]
Sur la page https://ikurso.esperanto-france.org/fr/cge/vocabula.php quand on tape une apostophe.

**Comment by pirboazo** [comment]
Hello Axel584,
Je viens d'installer sur une VM ikurso & je ne constate pas l'erreur que j'ai rapporté hier. :-(

Je reçois le message  "Erreur interne, contactez les administrateurs" , je constate que la page n'est plus en erreur .

Par contre dans le log apache j'ai l'erreur.

> `PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'l'%')  order by eo' at line 1 in /home/pboizot/src/ikurso/webui.inc.php:963\nStack trace:\n#0 /home/pboizot/src/ikurso/webui.inc.php(963): PDO->query('SELECT eo,fr,vo...')\n#1 /home/pboizot/src/ikurso/ajax/rechercherVorton.php(5): vortlisto('', 'CG', 'l'')\n#2 {main}\n  thrown in /home/pboizot/src/ikurso/webui.inc.php on line 963,`

Y a  t il une différence de version entre le code de la version production et celui de github ?

**Comment by axel584** [comment]
Non, il n'y a pas de différence (normalement). Tout d'abord, bravo à toi pour avoir installé ikurso sur une VM 👍 
J'ai essayé de simplifier au maximum son installation pour des personnes qui voudraient nous aider, mais c'est encore très compliqué (installer la structure de la base, puis les données applicatives et enfin les données de test... ) Mais sachant qu'il n'y a que les bénévoles qui participent à l'élaboration d'ikurso qui ont besoin de l'installer, je ne peux pas perdre trop de temps à faire un installateur.
Pour revenir à ton absence d'erreur en local, il s'agit sans doute d'une question de configuration de php qui va afficher certains types d'erreur (warning, error) soit dans la page, soit dans les logs.
Par exemple, en local, je vois des warning sur certaines pages (que je profite pour corriger), mais ces warnings n'apparaissent pas en prod.

**Comment by pirboazo** [comment]
Saluton Axel,

J'ai trouvé une solution. 
appel de  normaligita dans  vortlisto

mais elle ne fonctionne pas car j'ai une erreur sur l'appel de la fonction mb_ereg_replace, 
[Thu Jan 16 18:15:51.543573 2020] [php7:error] [pid 800] [client 192.168.56.1:59268] PHP Fatal error:  Uncaught Error: Call to undefined function mb_ereg_replace() in /home/pboizot/src/ikurso/util.php:62\n

Je ne comprends pas pourquoi !!!  Peut-être une histoire de version . j'ai un php 7.3 

Par ailleurs j'ai un probleme d'include_path ... Mail.php not found.

Je regarderai les fonction facile ... ;-)

A+
Pierre
