### ISSUE TITLE
Difficile de valider le dernier mot du vocabulaire

### ISSUE THREAD

**Issue by Cauryl** [axel584/ikurso#966]
Le mot n'est pas validé et est rechargé juste après l'`alert()`. Il faut insister et recommencer plusieurs fois pour valider.

![ikurso](https://user-images.githubusercontent.com/58689680/86397761-b70d9300-bca4-11ea-9def-4f2308cd73bb.png)

**Comment by axel584** [comment]
Saluton Cauryl,
Je n'ai pas réussi à reproduire le problème. 
L'alert signifie un problème dans l'appel ajax. Du coup, il faudrait regarder dans l'inspecteur d'éléments, dans l'onglet "réseaux" pour voir l'appel au programme kontroliVorton.php et m'indiquer l'url complète (j'ai besoin des paramètres mis dans l'url), ainsi que le contenu "json" du résultat.

Si tu as des difficultés pour me fournir ces informations, n'hésite pas à me demander, je pourrai t'aider à récupérer les informations qui nous permettront de corriger le problème (si le problème peut se corriger).

Autre possibilité, il s'agit d'un problème ponctuel d'accès au serveur (problème réseau) et qui s'est résolu tout seul. Et là, il sera plus difficile de corriger.

Axel

**Comment by Cauryl** [comment]
Saluton !

J'ai réussi à identifier le moment où le comportement se manifeste.

J'ai fait une séance de révision normale avec plusieurs erreurs.
Ensuite, j'ai directement relancé le cycle de révision avec le
vocabulaire disponible. À cause d'une faute de frappe, il ne restait
qu'un seul mot à réviser. C'est au cours du cycle de révision du mot
unique que le bug est réapparu.

Cette fois, le mot a été validé à la deuxième tentative. Je n'ai pas
l'habitude de la console et je n'ai pas réussi à récupérer les
informations juste après l'erreur.
À la prochaine révision, je provoquerai le bug et je posterai l'url et
le json.

Juste pour confirmation, c'est bien le json et l'url attendus, n'est-ce
pas ?

```json
{"mesagxo":"ok"}
```

```
https://ikurso.esperanto-france.org/ajax/kontroliVorton.php?vorto_id=1395&persono_id=15628&respondo=floro
```

**Comment by axel584** [comment]
Saluton,
C'est bien le json et l'url qu'il faut indiquer.... mais là, c'est le cas où les choses se passent bien :-) 
Du coup, si tu arrives à reproduire le problème, tu pourras indiquer le json du cas où ça plante.
Merci à toi,
amike,

**Comment by Cauryl** [comment]
À l'instant, je viens de lancer une révision. J'ai donné une mauvaise
réponse en guise de dernier mot, encore et encore. Mais rien de bizarre
cette fois.

Peut-être que c'était bien un problème côté serveur ?

**Comment by axel584** [comment]
Donc, on peut fermer ce ticket, n'hésite pas à le réouvrir si tu réussis à reproduire le problème et trouver le résultat json/url qui permette de voir le problème.

**Comment by Cauryl** [comment]
J'ai fait les séances de révisions avec la consoles ouvertes exprès pour récupérer le json.
J'ai constaté à chaque fois qu'après le message d'alerte (rapide, oublié de le préciser), la page est directement rechargée et donc je ne peux rien récupérer.

**Comment by axel584** [comment]
Dans ce cas, il faut cliquer sur "preserve log" dans l'onglet "network" de la console.
C'est néanmoins surprenant car cette page de révision fonctionne en ajax, elle ne devrait pas recharger la page...
