### ISSUE TITLE
Mettre à jour les explications sur les claviers en espéranto

### ISSUE THREAD

**Issue by emmrichard** [axel584/ikurso#97]
page helpo.php

Voir infos sur http://arrasesperanto.free.fr/ecrire.htm

**Comment by axel584** [comment]
Si on repompe, ne pas oublier de leur envoyer un mail pour leur demander leur accord

**Comment by emmrichard** [comment]
reçu d'un élève :
Dans le site (FAQ / Clavier français-espéranto pour Windows) le lien http://ttt.jubilo.ca/ttt/clavier/ est
"mort".

**Comment by emmrichard** [comment]
voir aussi http://eo.esperanto.org.nz/how-to-learn-esperanto/how-to-type-esperanto-characters
