### ISSUE TITLE
Avis mitigé d'un correcteur sur la page de correction

### ISSUE THREAD

**Issue by dfriquet** [axel584/ikurso#982]
Bonjour, bonjour,

Je ne sais pas trop où vous transmettre ce commentaire de mon correcteur :

![S'il vous plaît, si possible, envoyez-moi les leçons par votre messagerie habituelle, comme un simple courriel ; c'est beaucoup plus facile à corriger et  à commenter....plutôt que de passer par le site.](https://user-images.githubusercontent.com/634957/98393304-6397c100-2059-11eb-88f3-498a078e8028.png)

De ce que je vois en tant qu'apprenant : il a toujours la possibilité de faire, comme dans ses courriels, une mise en forme riche (gras, italique, couleurs…), mais pas la possibilité, comme il le faisait dans les courriels, d'ajouter du style directement sur ma réponse, et peut-être pas la possibilité de joindre des fichiers.

À toutes fins utiles :man_shrugging:

**Comment by dfriquet** [comment]
Une idée : envoyer à la fois le courriel vers la nouvelle page de correction, mais également le courriel "traditionnel", celui que je reçois encore en tant qu'apprenant à la validation de la leçon.

Ainsi, le correcteur a le choix des armes : courriel ou iKurso.

Et pour éviter d'envoyer deux courriels (empreinte écologique, tout ça), insérer le lien vers l'outil iKurso au début du courriel "traditionnel" pour le correcteur.

Tout ça en attendant d'atteindre, par la discussion et d'éventuelles nouvelles fonctionnalités, le contentement de tous les correcteurs :crossed_fingers:

**Comment by axel584** [comment]
En fait, on envoie bien les deux messages. La différence c'est qu'on envoie la leçon via le serveur smtp de notre serveur esperanto-france.org (et avec l'adresse email de l'élève comme expéditeur) et le message avec le lien vers l'outil de correction en ligne via le serveur d'Amazon SES (avec l'adresse ikurso@esperanto-france.org comme expéditeur).
Et le problème c'est que le premier mail (celui qui inclue le contenue de la leçon) est parfois/souvent considéré comme spam par le destinataire.

**Comment by dfriquet** [comment]
Ce qui fonctionne assez bien dans le premier cas, c'est d'envoyer également avec l'expéditeur ikurso@esperanto-france.org mais avec un `reply-to` vers l'adresse de l'élève.

Ce n'est pas parfait, mais ça passe beaucoup plus de filtres anti-spams.

**Comment by axel584** [comment]
Oui, c'est ce que l'on fait (enfin je crois de mémoire, à vérifier dans la classe util.php)
Pendant plusieurs mois, on a eu des gros soucis de blacklist de notre serveur et c'était très handicapant, c'est d'ailleurs suite à ces problèmes que l'on a mis en place les outils pour corriger en ligne...
D'autre part, l'avantage de la correction en ligne, c'est que pour le correcteur, on a accès à un corrigé type et pour le système, on a une base de données des réponses acceptées par les correcteurs.

**Comment by dfriquet** [comment]
Je vois, c'est effectivement ce qui est fait dans `util.php`. J'ai récemment eu recours à [Mail-Tester](https://www.mail-tester.com/) pour améliorer le score de nos serveurs d'envoi ; si jamais ça peut être utile.

Ne voyant rien à ajouter, je vais fermer ce ticket et simplement informer mon correcteur que, s'il préfère ce canal de correction, mes exercices sont probablement dans ses spams :information_source:
