### ISSUE TITLE
Corriger les fichiers sql pour une installation de développement

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#985]
erreur sur la page : 
http://localhost/ikurso/fr/cge/lec01.php?section=10

=> 

Array ( [0] => 42S22 [1] => 1054 [2] => Champ 'korekto' inconnu dans field list ) 1

**Comment by mcorne** [comment]
après avoir installé create-database.sql, create-data.sql et create-data-test.sql, j'ai dû exécuter les requêtes suivantes pour corriger les erreurs dues à des champs manquant, telle que ci-dessus
```sql
ALTER TABLE `ekzerceroj` ADD `poentoj`       INT(11)   AFTER `korektebla`;
ALTER TABLE `ekzerceroj` ADD `respondmodelo` TEXT      AFTER `demando`;
ALTER TABLE `respondoj`  ADD `korekto`       TEXT NULL AFTER `gxusta`;
```
