### ISSUE TITLE
Problème dans l'envoi des messages quand un titre à une apostrophe ou une lettre accentuée

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#989]
On peut le reproduire dans le formulaire de contact

**Comment by mcorne** [comment]
je n'arrive pas à reproduire le pb avec une apostrophe et un accent dans le titre (ni dans le corps du message d'ailleurs) avec le formulaire de contact, voici un ex d'email reçu sur ma boite mail conforme à l'envoi :

![image](https://user-images.githubusercontent.com/1748939/185412413-402d9dcd-ac4d-4abf-bc0d-fb51cff0cea7.png)

**Comment by axel584** [comment]
en effet, je n'arrive pas non plus à reproduire le problème, je clos le ticket. merci pour ta vigilence.
