### ISSUE TITLE
Corriger l'exercice 4 de la page 6.12

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#992]
Retirer "LA" pour former la phrase : 
En Arkto estas blankaj ursoj

**Comment by mcorne** [comment]
voici le patch
```sql
UPDATE `ekzerceroj` SET `demando` = 'arkto - blankaj - en - estas - ursoj.' WHERE `ekzerco_id` = 25 AND `kodo` = 'ekz06_31';
```

**Comment by axel584** [comment]
@mcorne : merci beaucoup, j'ai corrigé en base. A noter qu'on n'utilise plus vraiment le champ "kodo" et qu'on préfère utiliser le champ "ekzercero_id" (ça impose d'avoir les mêmes identifiants en local et en prod, mais c'est plus simple à gérer), du coup, tu verras dans la fin du fichier changelog.sql qu'on fait des insert en indiquant l'id à utiliser et on n'utilise plus l'autoincrement de mysql.
