### ISSUE TITLE
corriger l'exercice sur les cxu

### ISSUE THREAD

**Issue by axel584** [axel584/ikurso#999]
https://ikurso.esperanto-france.org/fr/cge/lec04.php?section=12

sur le dernier exercice de la page, il faudrait que les questions soient en espéranto et ajouter peut-être un exemple de question/réponse (positive ou négative)

**Comment by mcorne** [comment]
voici le patch avec la traduction en espéranto
```sql
UPDATE `ekzerceroj` SET `demando` = 'Ĉu la lakto estas malvarma?'                  WHERE `ekzerco_id` = 19 AND `kodo` = 'ekz04_28';
UPDATE `ekzerceroj` SET `demando` = 'Ĉu vi gustumis la kukon?'                     WHERE `ekzerco_id` = 19 AND `kodo` = 'ekz04_29';
UPDATE `ekzerceroj` SET `demando` = 'Ĉu lia edzino estas la patrino de via amiko?' WHERE `ekzerco_id` = 19 AND `kodo` = 'ekz04_30';
UPDATE `ekzerceroj` SET `demando` = 'Ĉu vi havas du eŭrojn kaj tridek cendojn?'    WHERE `ekzerco_id` = 19 AND `kodo` = 'ekz04_31';
UPDATE `ekzerceroj` SET `demando` = 'Ĉu vi vidis la novan teatraĵon?'              WHERE `ekzerco_id` = 19 AND `kodo` = 'ekz04_32';
```
par contre je vois déjà des exemples de réponse dans les champs respondo et normaligita

**Comment by axel584** [comment]
@mcorne : historiquement le cours était en version papier (et doit être assez ancien), et l'évolution des pédagogies poussent à éviter autant que possible de "traduire" (alors que le cours est rempli de d'exercices de traduction). Mais un exercice où la question est en français et on demande à répondre à la question dans une autre langue, est vraiment une question casse gueule :) ...
Merci beaucoup pour ton patch, je l'ai appliqué en prod
